INSERT INTO ONLINE_ORDER (ID_Online, TimeOrder) VALUES (ID_Order, '06:18:56');
INSERT INTO ONLINE_ORDER (ID_Online, TimeOrder) VALUES (ID_Table, '10:55:07');
INSERT INTO ONLINE_ORDER (ID_Online, TimeOrder) VALUES (ID_Customer, '13:02:43');
INSERT INTO ONLINE_ORDER (ID_Online, TimeOrder) VALUES (ID_Review, '01:00:59');
INSERT INTO ONLINE_ORDER (ID_Online, TimeOrder) VALUES (ID_Employee, '01:40:04');
INSERT INTO ONLINE_ORDER (ID_Online, TimeOrder) VALUES (ID_Branch, '00:42:26');
