INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 1, 1, 5, 'Training yeah seek modern every wind.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 3, 2, 3, 'Population perform mouth huge since.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 2, 2, 2, 'Nothing end whole bit modern toward himself audience.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 3, 4, 4, 'Attention herself gas.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 3, 2, 3, 'Reach daughter Mrs cover team.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 2, 2, 4, 'Night right degree story effect plan own.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 4, 2, 3, 'Short play sell cause friend rest fight.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 1, 2, 5, 'Wonder teach level number everyone will machine.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 1, 3, 5, 'Air capital bit car might industry industry.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 3, 2, 1, 'No company citizen good around.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 2, 1, 2, 'Involve knowledge resource economic another job from win.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 5, 3, 3, 'Since series eight subject understand trouble.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 1, 2, 3, 'Gas miss they shake.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 3, 4, 1, 'Together stage well.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 4, 2, 4, 'Program watch hundred growth serious share never.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 2, 4, 5, 'Realize arrive kitchen act.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 1, 3, 5, 'Message director scientist cover.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 1, 4, 3, 'Pull marriage capital stage effort low back.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 1, 5, 3, 'Age by fear half itself.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 5, 3, 3, 'Out data night everybody when box student better.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 3, 1, 3, 'Identify blue someone nearly police lot name.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 4, 5, 4, 'Positive always past thousand claim everything director.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 5, 3, 4, 'Room fact nothing close piece.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 2, 5, 4, 'Bill part finally building state receive among.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 4, 4, 1, 'Though meeting of avoid reason show.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 3, 5, 1, 'Name across happy floor great everybody it.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 4, 2, 1, 'Position ever such single dinner.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 5, 5, 4, 'Article although run move reach word consider.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 1, 1, 1, 'Sign risk necessary like health Mrs.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 2, 5, 3, 'Look up interesting fire their issue.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 5, 2, 3, 'Whole condition again doctor lose business now.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 5, 2, 4, 'Particular behavior explain notice about purpose.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 5, 1, 2, 'His food development thus.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 1, 5, 1, 'What party teacher report.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 2, 2, 2, 'Dinner grow when way same matter moment.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 1, 5, 2, 'Behavior left team pay.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 2, 1, 2, 'What talk white party base without pay every.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 3, 5, 1, 'Reach fall kitchen current better experience wife society.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 1, 4, 3, 'Receive and responsibility nothing through lead low.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 5, 2, 5, 'Difference myself quality table economy PM on.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 2, 4, 1, 'Story decide air easy line.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 5, 2, 5, 'Heart house east commercial.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 5, 3, 4, 'Stop sell speech tell through reveal sound.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 5, 4, 1, 'Purpose American music feeling this with police.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 3, 1, 4, 'Nature could particular cause.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 3, 1, 3, 'Seem have news want really at.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 5, 4, 4, 'Door various southern others I.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 1, 2, 2, 'Soon stage something meeting long total save same.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 2, 5, 4, 'Without worry maintain sell attention.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 3, 3, 3, 'Remain way get their relate.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 4, 2, 4, 'Garden determine enjoy one black.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 5, 4, 4, 'Student half economy thing.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 1, 4, 5, 'New very few hit different put.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 3, 4, 2, 'Thing fish feeling hard great money explain.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 3, 2, 1, 'Ability may grow fight TV.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 1, 4, 2, 'American coach ago crime great effect.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 5, 3, 4, 'Serious share seek his five.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 4, 3, 3, 'Enough on south describe vote building public.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 2, 3, 5, 'Hotel state attention conference.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 3, 5, 2, 'Bed society you within picture girl today.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 4, 2, 5, 'These opportunity worry which movie media.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 2, 5, 4, 'Also board travel car student term.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 4, 3, 1, 'Among item our head set.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 3, 5, 3, 'Word your society night purpose before.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 1, 4, 4, 'Agency church approach I by seat.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 3, 4, 1, 'Million visit watch husband.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 3, 2, 5, 'Pattern energy notice how up.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 2, 2, 2, 'Loss piece month.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 4, 4, 5, 'Political section stock create individual act production.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 4, 5, 4, 'Affect agreement which.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 5, 5, 3, 'Food human kitchen offer respond way east hear.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 3, 5, 3, 'Environment provide maybe.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 5, 5, 5, 'Stand key price page.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 3, 1, 3, 'Fish ok technology side last day.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 2, 5, 3, 'Resource indicate choose international quality floor.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 4, 4, 4, 'Affect never believe move gun work.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 4, 4, 4, 'Source face piece but responsibility.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 5, 5, 1, 'Law build could concern so.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 5, 1, 2, 'Nature team out seem cost we.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 5, 5, 2, 'Catch certain soon agreement company.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 1, 3, 3, 'Cause situation high who take skin.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 2, 2, 1, 'Large boy activity unit reality.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 1, 2, 4, 'Decide truth few theory set dream.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 4, 4, 1, 'Unit agency item eight sea throw my.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 5, 3, 5, 'Per already statement open fish reach.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 1, 4, 4, 'Quite part job quite kind worry.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 2, 1, 1, 'Church under although debate tend time.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 1, 4, 1, 'Man should everyone meeting development name make option.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 1, 2, 1, 'Set purpose probably sell expect available national.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 1, 3, 4, 'Next production purpose rock ever.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 5, 2, 2, 'Understand certainly himself security night.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 2, 4, 1, 'Term owner form dog age they real watch.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 5, 1, 5, 'Gas late together.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 5, 1, 2, 'Game program and unit us management.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 3, 2, 5, 'Company number thank black sometimes.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 2, 3, 1, 'Someone hope toward study past.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 1, 5, 1, 'Rest bit history what benefit short.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 2, 1, 5, 'Outside strategy technology one.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 5, 2, 5, 'Everybody election product.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 4, 4, 5, 'Language everyone hard fear.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 5, 5, 5, 'Painting defense film say her.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 1, 1, 3, 'Popular everything long return court trouble despite continue.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 4, 2, 4, 'Daughter back option free.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 5, 5, 5, 'From building discover military fast avoid.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 3, 2, 3, 'Whose short follow same friend.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 1, 3, 4, 'Size reason dream radio its camera.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 5, 5, 4, 'Almost political hair science.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 4, 2, 2, 'Walk reach money say yeah vote.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 2, 2, 2, 'Show his media find rest interest.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 4, 1, 4, 'Public stage fill town.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 3, 3, 5, 'Admit even north area.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 5, 3, 1, 'Say simply after create why smile painting.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 1, 5, 2, 'Debate why institution nearly glass cause.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 3, 5, 5, 'Spring exist girl local production consider single.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 5, 3, 2, 'Those audience shoulder dark between.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 3, 1, 2, 'After talk likely series clearly.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 3, 3, 1, 'Number help accept north kind enjoy growth.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 5, 3, 4, 'Truth single determine imagine.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 4, 2, 4, 'Education management become.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 4, 4, 3, 'Anything few American land customer politics Republican hit.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 2, 2, 5, 'People along key perform.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 4, 4, 4, 'Nice son herself bed unit this instead different.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 4, 3, 5, 'Before military individual show.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 2, 1, 4, 'Order cup least bill economy total tell.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 2, 3, 2, 'Fear station perform simply.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 2, 5, 2, 'Include boy country entire field.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 4, 5, 5, 'List through area age accept serve program.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 3, 1, 3, 'Buy serious large minute everyone individual leave defense.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 1, 3, 5, 'Magazine medical despite result indicate before.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 4, 4, 4, 'Thank appear smile science approach improve.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 1, 3, 1, 'Television about choose live ready.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 2, 5, 1, 'Door window natural director.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 1, 2, 1, 'Million join growth old glass.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 2, 4, 2, 'Game think generation program agent.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 3, 2, 2, 'Tv identify quickly.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 1, 4, 2, 'Worker within add debate interview describe.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 4, 2, 2, 'Section agent new attorney official by.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 5, 5, 5, 'Bill discussion find move page wall three.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 5, 3, 4, 'Those task amount still whole guess.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 5, 5, 3, 'Possible production or everything.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 5, 2, 2, 'Professional enter also put deep speech they.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 1, 3, 2, 'School drive but over product value.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 3, 4, 5, 'Very stock store great senior certainly rise.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 5, 4, 2, 'Account prevent politics they everybody.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 1, 5, 4, 'Lead add also pull religious sure.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 3, 5, 2, 'Friend reflect great manager friend become language.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 1, 4, 3, 'Political will way travel cover.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 2, 2, 1, 'Only visit front serious low.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 5, 2, 5, 'Whatever speech present then music else.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 2, 1, 3, 'Ok finish form moment.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 3, 5, 2, 'Represent catch tree including behavior less point.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 1, 4, 4, 'Area specific indicate within enjoy particularly major.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 4, 5, 1, 'Glass magazine research away require modern step.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 4, 3, 5, 'Lawyer another price structure out bar.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 5, 3, 1, 'Nature memory leader produce from much second wide.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 1, 4, 2, 'Rule relationship action different house morning population.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 4, 2, 4, 'Trouble budget in.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 1, 5, 5, 'Rule subject head should.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 1, 4, 3, 'Available lead development PM.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 4, 1, 4, 'Nearly wind level government cell collection wonder.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 3, 3, 1, 'Arrive bank religious develop decide article perhaps.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 3, 4, 1, 'How industry black.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 1, 2, 4, 'Control far hand discover sign drug job.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 4, 3, 3, 'Plant special answer financial.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 2, 3, 2, 'Pressure read letter.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 2, 5, 4, 'Represent growth quickly prepare red story.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 3, 4, 2, 'Reach soldier understand support artist blue budget guy.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 2, 2, 4, 'Not cause color across interview.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 5, 5, 3, 'Style picture hour art remain war.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 3, 5, 4, 'Senior speech often choice.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 2, 2, 4, 'Fire trouble artist create future former magazine.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 1, 2, 3, 'Thank newspaper plant science environmental.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 2, 1, 2, 'Serious medical begin table edge.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 4, 1, 1, 'Former could need way because design serious.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 3, 3, 2, 'Reach short edge his Congress.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 4, 1, 4, 'Vote up better receive.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 4, 3, 5, 'Thing others remain child memory.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 1, 3, 3, 'Move agree everyone action.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 5, 2, 4, 'President hospital all away have attack head bag.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 3, 5, 2, 'School tough computer window particular.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 4, 2, 4, 'Budget miss three cut though let whose.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 1, 1, 1, 'Yard six red minute.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 4, 2, 1, 'Week miss bit.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 1, 1, 2, 'Anyone executive build yard.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 2, 3, 3, 'Particular support full every through feeling.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 4, 5, 4, 'Sign young fact role I piece can require.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 1, 4, 1, 'Economic space individual finally type.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 3, 5, 4, 'In college medical employee treat something.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 4, 4, 4, 'Less of significant establish blood candidate.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 3, 4, 5, 'Man capital similar star painting speech.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 5, 4, 5, 'Traditional avoid everybody perhaps identify region.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 1, 5, 1, 'Space go wife song pressure.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 1, 1, 3, 'For each indeed reason and seek include.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 3, 3, 5, 'Wait plan modern help realize drive.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 2, 4, 5, 'Event five might miss action second.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 4, 1, 3, 'As half degree on.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 1, 1, 5, 'Sell dream heart try school owner seat might.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 3, 4, 2, 'Television occur movement.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 4, 1, 3, 'Risk impact need drive investment bring shoulder want.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 5, 3, 1, 'Care look art mother.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 1, 5, 3, 'White become hear state.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 1, 3, 1, 'Peace authority thank activity arm college.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 5, 2, 2, 'Name single pull wonder safe yeah.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 1, 4, 3, 'Again during yes eat rock.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 4, 1, 1, 'Old management then meeting task part.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 4, 5, 2, 'Able stay story hear summer thought why.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 3, 1, 3, 'Popular program see general shake.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 3, 4, 1, 'About age safe character media.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 2, 4, 3, 'Manager style piece certainly really tax positive.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 4, 4, 1, 'Home floor party about.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 1, 5, 4, 'Once seat upon man way mother admit floor.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 3, 5, 1, 'Ok compare of card.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 5, 1, 1, 'Number indeed feeling off clearly participant four.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 3, 2, 1, 'Week range recently her Democrat message take.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 5, 2, 2, 'Return decision watch nothing while watch get.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 5, 5, 1, 'Service thousand service provide.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 2, 1, 2, 'Case measure again raise and.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 3, 4, 3, 'Test practice degree these customer.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 5, 3, 1, 'Forget crime discover case.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 5, 2, 4, 'Wife art free agreement score our by force.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 1, 5, 5, 'Key peace subject detail charge serve war billion.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 4, 1, 1, 'Instead water possible later air build create.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 4, 2, 1, 'Name seat his set coach.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 1, 5, 5, 'Radio finish spring believe whatever in.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 4, 4, 1, 'Base small direction similar four agency fish.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 1, 1, 1, 'Month although member base state feeling single language.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 5, 4, 4, 'Relationship develop party final.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 2, 3, 1, 'Cultural onto agreement statement politics after opportunity.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 3, 3, 5, 'American computer team today type learn after executive.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 4, 2, 4, 'Thought question kid outside.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 5, 3, 4, 'Unit night build partner child program.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 3, 3, 4, 'Before civil entire discuss piece argue.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 3, 1, 5, 'Magazine law million money baby.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 4, 2, 4, 'Large type miss also.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 1, 3, 1, 'Which land network point he benefit itself.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 3, 3, 3, 'Story relationship indeed hundred ten budget baby.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 2, 5, 2, 'Choice purpose table only thousand spend office.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 4, 4, 3, 'Ball factor state per any instead.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 5, 5, 4, 'Structure two figure whom news gas.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 1, 2, 4, 'Small success good.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 2, 3, 1, 'Case cup network ask still serious.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 1, 1, 5, 'Each affect popular money realize partner.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 1, 4, 3, 'Later soon number control wrong start hit.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 4, 5, 5, 'Position information moment administration grow central need.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 5, 4, 2, 'Identify opportunity pay us personal another.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 1, 2, 1, 'Manager start simply know be relate benefit.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 2, 5, 3, 'To back song identify soldier where general.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 4, 3, 1, 'Cell matter year history late foot.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 3, 4, 1, 'Officer grow wind hope among wonder pressure.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 3, 1, 1, 'Enjoy word foot save participant wall.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 1, 2, 4, 'Serious movement about capital else.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 4, 5, 2, 'Provide out it.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 3, 4, 4, 'Center note move administration whatever.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 1, 2, 1, 'Leader difficult happy radio management already process task.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 3, 1, 1, 'Do so similar partner.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 3, 5, 5, 'Field improve item.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 5, 2, 5, 'A before save oil describe wind foreign.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 3, 5, 1, 'Bill today everybody figure environment bar.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 1, 4, 4, 'Draw address voice nor size production compare.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 1, 2, 1, 'Every of kind network.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 4, 1, 2, 'Travel continue as.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 4, 1, 5, 'News whole tend window trouble address.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 5, 3, 4, 'Detail kid like interview.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 1, 2, 2, 'Almost whether wait.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 3, 2, 3, 'Sell through particularly probably one.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 1, 4, 5, 'Artist create evidence movie light better this.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 3, 2, 2, 'Would statement mouth still contain.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 4, 5, 3, 'Your now why book test arrive popular.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 2, 3, 1, 'Father to since yard loss feeling rate data.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 1, 4, 3, 'Water only window prove recognize describe.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 2, 4, 2, 'Ask easy myself standard.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 1, 3, 5, 'Reflect no others can support meeting drug deal.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 2, 5, 1, 'Suddenly unit benefit involve ground store.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 5, 5, 5, 'Treatment space power stage style.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 5, 1, 1, 'Property point drop whole.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 2, 1, 5, 'Along law face place culture dream.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 5, 4, 2, 'Military power even whose.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 5, 5, 3, 'Congress site science avoid suffer.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 1, 5, 4, 'Allow teach senior loss the myself.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 2, 4, 1, 'Speak society affect she matter play PM.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 2, 2, 2, 'Then among after reveal most none imagine you.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 1, 1, 1, 'Story message simply finally and toward trial.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 1, 4, 5, 'Box TV color measure.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 5, 3, 4, 'Media threat moment day return politics.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 5, 2, 1, 'Month money number girl southern.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 2, 4, 5, 'Movement room market letter floor.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 1, 2, 1, 'Cut to very watch unit.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 5, 5, 4, 'Range writer politics administration growth world.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 5, 4, 3, 'Nothing less attack security they piece by.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 3, 5, 5, 'Big when term physical act region.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 3, 2, 5, 'Former knowledge others author.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 1, 3, 1, 'The sort energy everybody drive.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 2, 4, 5, 'Opportunity law could prevent about response.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 5, 5, 5, 'Possible tough market work.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 2, 3, 5, 'Religious safe eat activity.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 2, 2, 3, 'Add vote poor city trial perform space.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 3, 5, 3, 'Pattern around hotel science back start.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 3, 2, 4, 'Painting add exist as world shoulder law.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 1, 5, 2, 'Wait discuss law at trip.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 2, 1, 2, 'So crime structure carry investment.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 1, 1, 2, 'Identify key home as to others one.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 4, 5, 5, 'Poor image picture those consider stay.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 2, 5, 3, 'Could spring avoid skill every condition.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 2, 4, 3, 'Glass style today eight once.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 4, 1, 3, 'Year likely former.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 2, 4, 3, 'Itself truth those couple.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 2, 3, 1, 'Provide interesting play many machine someone.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 3, 1, 5, 'Federal practice this check a site stock exist.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 1, 1, 3, 'Speech thought understand power.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 2, 1, 5, 'Leader customer sister in thought quickly citizen.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 5, 4, 2, 'Military just answer good fact.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 3, 3, 4, 'Edge scientist understand Congress find national institution weight.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 2, 3, 4, 'Bed future wife list explain fish red dog.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 5, 5, 1, 'Rule side house finish fill.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 4, 3, 3, 'Treatment face real information network.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 4, 5, 5, 'Either entire finish three per debate site.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 2, 3, 2, 'Relate father measure.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 2, 5, 2, 'Operation and part thus stuff.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 3, 4, 5, 'Health your common arrive movie pattern myself.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 2, 3, 4, 'Crime road wide imagine among heart.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 3, 4, 1, 'Thing food amount.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 5, 5, 2, 'Assume scene anything show.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 5, 3, 5, 'Particularly owner morning over.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 1, 1, 1, 'Mission total themselves bank threat.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 4, 5, 4, 'World course decide space either mean design whether.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 3, 3, 2, 'Former month month firm establish.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 2, 2, 2, 'Teacher production method coach describe industry sell modern.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 4, 5, 5, 'Deal next note could.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 4, 2, 5, 'Name positive building southern.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 3, 4, 1, 'Agent must friend land everything beyond white.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 4, 2, 4, 'Each say stage.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 1, 5, 1, 'Learn her current fill.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 3, 4, 3, 'Serve recognize open really investment crime.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 4, 1, 2, 'Move test service short.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 3, 2, 1, 'Likely fine best story.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 1, 3, 1, 'Which staff box fear amount available.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 5, 3, 3, 'It sometimes successful the free society.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 4, 4, 5, 'Marriage gas pick.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 2, 4, 3, 'Investment side call consider.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 2, 1, 2, 'Partner mother though former off no white color.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 1, 3, 2, 'Republican charge unit enough send carry letter.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 3, 3, 5, 'Lay what society meet focus such.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 5, 1, 1, 'You boy ground right control almost never.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 5, 4, 5, 'Culture development high activity several hit.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 1, 3, 3, 'People decision miss look other own century.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 2, 1, 2, 'Program charge maybe then religious land nature concern.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 4, 3, 1, 'Buy score evidence role.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 1, 5, 1, 'Plan she cut baby.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 3, 2, 5, 'Of deep conference picture camera.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 3, 3, 5, 'Base within difference.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 1, 3, 5, 'Understand kid across role admit resource run.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 2, 3, 3, 'Human college rise cost close.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 5, 5, 3, 'Worker kind star model factor senior.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 1, 4, 3, 'Since form campaign.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 2, 5, 5, 'Involve prove minute hard a.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 4, 1, 5, 'Brother group teacher control attorney Democrat along.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 2, 1, 2, 'Change may respond political language hundred world answer.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 5, 5, 2, 'Goal coach from actually story bed.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 5, 2, 5, 'Remain reason town daughter whom customer.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 1, 5, 1, 'Tend possible effort produce everything know myself.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 4, 1, 2, 'Agent down deal.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 3, 4, 5, 'Effect story bed.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 1, 1, 4, 'As far at time television.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 2, 5, 2, 'Father system significant assume occur game president.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 5, 3, 3, 'Yes beyond state happen chance next.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 4, 5, 3, 'Easy this almost technology.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 4, 4, 2, 'Color three improve stock central whether hour.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 3, 1, 5, 'Message dinner moment per building peace enter.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 1, 1, 3, 'Executive image theory consumer.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 5, 1, 3, 'Discuss social alone life five certainly brother.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 5, 5, 4, 'Course purpose step could effort reflect.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 3, 1, 3, 'Recently family tax health.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 3, 1, 4, 'This expert recently before.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 3, 1, 1, 'Baby sport degree member start feel project risk.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 3, 5, 4, 'Congress affect fast run.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 5, 2, 3, 'Moment couple already scientist family sit role.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 4, 2, 1, 'Fine goal assume nice drug to apply.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 1, 5, 5, 'Shoulder career which.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 3, 2, 2, 'Voice high Mrs gas before difficult must.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 2, 4, 2, 'Democrat effect laugh section movie.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 3, 1, 2, 'Both knowledge dinner compare.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 5, 3, 4, 'Camera their treat crime claim writer.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 1, 5, 2, 'Leg since project visit experience.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 3, 1, 2, 'During far information child.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 1, 2, 3, 'Information source color remain maintain onto mouth fall.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 5, 4, 4, 'Outside room risk instead.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 1, 3, 4, 'Computer agreement ago he yes change hour.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 3, 2, 1, 'In agree whose bank will follow public.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 1, 3, 1, 'Question deep wait modern cultural.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 3, 3, 4, 'Green yard cup generation tax guess you.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 1, 3, 4, 'Sea laugh who pull clearly.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 3, 2, 1, 'Computer key already growth history our.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 5, 2, 4, 'Source left challenge current production on provide much.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 3, 1, 3, 'Couple who step throw general give understand.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 1, 3, 4, 'Yes five five law dark.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 3, 2, 1, 'Authority describe enter evidence pull through concern.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 2, 2, 2, 'Against ever article wonder already.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 3, 1, 2, 'Impact person record TV quite together window toward.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 1, 5, 1, 'Hotel page Mrs knowledge.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 4, 5, 3, 'Measure commercial important.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 1, 3, 2, 'Bed rather thousand investment ball.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 5, 5, 2, 'World type deal standard stand real shake.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 3, 1, 4, 'Serve message collection study Congress scientist.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 2, 5, 5, 'Same race every majority life.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 2, 3, 2, 'Forget mission now lot same enjoy.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 4, 3, 1, 'Data much article poor drive picture paper.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 3, 1, 4, 'Concern ready less.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 5, 2, 5, 'Just manage trade knowledge.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 3, 4, 3, 'Fire kind at store management piece.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 3, 1, 1, 'Remain understand deal once.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 3, 3, 1, 'Decision along truth just toward contain industry.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 3, 1, 4, 'Six themselves start phone make treat strategy.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 2, 5, 1, 'Sense grow growth agreement.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 1, 5, 5, 'Price structure special throw.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 2, 5, 3, 'Military though important open particularly yourself be million.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 4, 1, 5, 'Must reality national leader.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 1, 5, 1, 'Concern station him describe produce.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 3, 2, 1, 'Decision hear poor enough his these.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 3, 3, 4, 'Husband poor performance.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 5, 1, 2, 'Chair radio beautiful he.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 1, 1, 3, 'Ball class city live around approach size.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 4, 5, 4, 'Go guess audience worker threat painting student.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 5, 4, 1, 'Some north science off where whom today.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 4, 4, 1, 'Which father memory move.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 5, 5, 1, 'Method executive report around painting none job.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 3, 2, 5, 'Father authority behavior feel.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 2, 5, 2, 'Painting news image actually wrong.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 1, 1, 1, 'Indicate way production drug media or increase.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 4, 3, 5, 'Story share put book.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 5, 2, 5, 'Another method follow magazine.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 2, 1, 1, 'His in wind continue interesting senior charge.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 1, 1, 4, 'Each tend economic.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 2, 1, 3, 'Investment finally pattern same.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 3, 2, 5, 'Discover evidence character long.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 1, 2, 3, 'Treat pretty over country itself statement.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 2, 3, 1, 'Current sure citizen dinner majority close lose.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 1, 5, 2, 'Nearly case sport stop certainly discussion certain.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 3, 3, 5, 'Public whole pressure claim statement charge.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 2, 4, 2, 'Race chair quite statement sea turn help.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 3, 3, 3, 'Pm friend his significant hour within page.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 2, 4, 4, 'While lay suddenly PM either road cell.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 4, 5, 5, 'All off style arrive building organization walk story.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 2, 2, 2, 'Fear go hand include role Congress.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 1, 3, 1, 'Western according wind plan admit painting think.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 3, 4, 1, 'Study they best.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 2, 2, 3, 'Physical base military order a shoulder despite old.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 5, 4, 4, 'Fast too weight difficult production street dog continue.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 3, 3, 3, 'Him economic history.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 2, 1, 4, 'Camera church list under staff.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 4, 5, 3, 'Southern get series sister want.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 1, 5, 1, 'Major democratic because foreign away threat.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 2, 3, 1, 'Stay every him great time.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 2, 2, 5, 'Evening almost half agency word.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 1, 4, 2, 'Sing determine later budget.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 2, 5, 5, 'Issue perhaps what whatever.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 4, 3, 5, 'Know study mention wait.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 2, 4, 1, 'Brother community decision attention leg above ground.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 2, 5, 5, 'Require themselves method cup.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 3, 3, 1, 'Focus else next task.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 5, 3, 4, 'Go particular magazine professor bill.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 1, 1, 5, 'Need marriage space community majority.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 3, 1, 3, 'Herself sign to seek.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 4, 1, 5, 'Material force build.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 3, 5, 2, 'About individual everyone child artist.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 3, 2, 3, 'Box campaign attack especially election yard thought.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 1, 5, 3, 'Process home number civil.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 1, 3, 1, 'Include group yard if air former.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 2, 3, 1, 'Conference sit statement bit.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 1, 3, 2, 'Ten until bring require.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 3, 4, 4, 'Hold entire technology moment anything toward.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 1, 1, 3, 'Film meet decision war war above image.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 2, 2, 4, 'Company life student outside just.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 5, 4, 2, 'Listen design nation report.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 3, 4, 3, 'Capital against case fund note spend.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 4, 3, 3, 'Play him window walk.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 3, 1, 1, 'Growth country gas sport decade.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 3, 5, 4, 'Enough student when.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 1, 4, 3, 'Sort account always vote public simply.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 1, 1, 4, 'Congress forward act dark staff so process.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 4, 1, 5, 'Reach community authority black Mr page.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 4, 5, 5, 'Site recognize or possible writer clearly bit fast.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 5, 1, 4, 'Program law institution though store.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 4, 3, 1, 'Exist worry entire always factor whose.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 3, 5, 3, 'Half customer address well cold study city.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 4, 5, 3, 'Positive vote agreement less product I.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 4, 3, 5, 'Cause soon series director single determine.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 1, 4, 3, 'Dream yourself record tell stuff.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 1, 5, 4, 'Mrs agent should.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 2, 1, 1, 'Sport share plant walk be.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 5, 4, 3, 'Shake generation total.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 4, 2, 2, 'Wait dog station dark push.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 1, 3, 2, 'Other yard soon local cup upon article.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 2, 3, 4, 'Walk moment try structure voice.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 1, 2, 1, 'Wife western order list hear measure challenge.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 4, 5, 3, 'Investment myself name traditional everything price carry.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 2, 2, 4, 'Participant start ready Congress explain and.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 2, 1, 5, 'Community sound evidence Mr value establish gas.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 5, 4, 2, 'Task hope ball life.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 2, 5, 5, 'Main person defense control.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 2, 1, 4, 'Staff soon say beautiful scientist art coach.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 5, 3, 5, 'Determine hundred interesting main computer allow six it.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 3, 3, 1, 'Deep question tough national environment return responsibility try.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 3, 1, 1, 'Chair cost boy cup fire difficult.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 5, 1, 1, 'Article feel contain material yes popular people moment.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 2, 3, 4, 'Congress Mr catch cultural.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 2, 5, 5, 'Television expert talk bad war see natural.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 4, 2, 5, 'Make everyone modern fill foreign.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 4, 4, 1, 'You population wind foreign begin former worker great.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 2, 3, 2, 'Prove enjoy inside.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 4, 4, 4, 'College book budget education.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 4, 4, 3, 'Something condition professional woman.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 5, 1, 2, 'Individual quality full live hope need do probably.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 4, 2, 3, 'Edge apply call.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 4, 1, 4, 'Town test say family.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 2, 3, 3, 'Them color cup him across not.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 1, 5, 2, 'Fine travel allow walk safe consider summer.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 2, 4, 4, 'Good institution section manager institution mouth attorney such.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 1, 1, 1, 'Try girl president technology.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 2, 4, 4, 'Center detail pressure increase.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 2, 1, 3, 'Place street north.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 3, 3, 3, 'Career safe begin ever language foreign.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 5, 4, 2, 'Democrat believe several else tend.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 5, 4, 2, 'Quite he run check analysis.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 2, 3, 3, 'Full visit police strategy score sit activity.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 2, 3, 3, 'Perform smile finish present return oil program.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 1, 3, 2, 'Certainly agency activity interest.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 2, 1, 2, 'Maybe would growth.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 3, 4, 5, 'Loss ten generation less study.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 5, 4, 2, 'Power save sense which.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 1, 3, 5, 'Hear move attorney position.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 3, 5, 3, 'Science run baby scientist crime add worker.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 5, 1, 1, 'House ever full option painting else argue.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 5, 3, 5, 'Now reason sense difference social adult.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 3, 2, 4, 'Service everybody significant evidence such.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 1, 2, 5, 'Program key huge enough meeting individual have.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 3, 5, 2, 'Cell ability song by.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 5, 1, 1, 'Let child week course painting start.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 1, 1, 3, 'Available nice quality mission be better assume drop.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 1, 1, 1, 'Term nearly glass soon.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 4, 4, 2, 'Nearly benefit cup organization reality.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 4, 4, 2, 'Fall about condition carry community here.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 4, 1, 5, 'Fast south letter make recognize material.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 5, 2, 1, 'Five Mrs everybody.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 3, 5, 3, 'Everyone people factor voice.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 3, 5, 2, 'Little computer that again computer day.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 1, 3, 4, 'Evidence whole amount.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 3, 2, 2, 'Girl fall deep recognize kind protect.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 1, 2, 1, 'Indeed community tough some good necessary interest.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 2, 4, 5, 'Under community success much per message to.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 2, 3, 1, 'Detail right its right number health head.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 2, 3, 2, 'Vote color painting cultural air majority.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 5, 3, 3, 'Raise movement realize free star identify would.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 2, 3, 2, 'Key base check ball that parent foreign.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 3, 5, 3, 'When upon practice relate measure data.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 4, 5, 3, 'Role certain somebody subject.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 3, 1, 1, 'Herself physical road include behavior.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 2, 4, 5, 'Throw price walk though should.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 2, 2, 5, 'Spend middle your.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 5, 1, 4, 'Similar contain else them they.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 5, 4, 3, 'Condition down weight black nation adult opportunity better.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 4, 2, 2, 'Week along morning discuss at.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 3, 3, 4, 'Gun short sport serious.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 4, 2, 4, 'Different open its condition.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 5, 2, 5, 'About official road dream itself might.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 4, 1, 2, 'Agent election should environment break little.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 5, 1, 1, 'Public thank physical pull benefit until base.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 5, 2, 5, 'Market sit relate.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 1, 1, 4, 'Teacher interview animal although miss.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 5, 4, 3, 'Glass law leave tough early.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 4, 1, 5, 'Five artist bank.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 3, 1, 5, 'Hair air trip third lose pull him box.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 3, 5, 2, 'Rise movie involve may fear million outside.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 3, 2, 5, 'Left beyond tax.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 2, 5, 2, 'Wait interesting military difference laugh help.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 5, 1, 1, 'Car audience read partner.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 3, 2, 5, 'A own one.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 2, 3, 3, 'Allow day tend clear on argue.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 1, 2, 5, 'History wall future simply.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 1, 2, 3, 'Fill land whatever.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 2, 5, 2, 'Real how indeed individual.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 2, 2, 3, 'Man attorney history shake.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 5, 1, 2, 'Direction born stop break.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 5, 1, 1, 'Adult charge fire discussion new.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 5, 5, 4, 'Control enter serious speak.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 3, 3, 3, 'Building situation official agreement dog.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 1, 5, 3, 'However drop girl artist.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 5, 2, 5, 'Into buy wall strategy care.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 5, 3, 1, 'Economic enter myself size white something cold.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 1, 1, 3, 'Cup tonight matter.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 2, 4, 4, 'Southern plant before or.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 1, 2, 3, 'Special professor some price natural character bit.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 2, 1, 4, 'Under subject industry hospital sit whatever travel.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 3, 2, 5, 'Collection body century nor.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 4, 3, 5, 'Step professor general next whose whole show.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 1, 4, 5, 'Foot sometimes dinner.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 2, 3, 1, 'Close man difference action card.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 1, 1, 1, 'Just value civil late visit Republican everyone.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 2, 5, 3, 'Do cultural letter other authority.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 5, 3, 1, 'Much compare year consider program.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 3, 3, 1, 'Pull pattern return painting.');
