INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 4, 2, 2, 'Own professor down growth keep choose gas.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 1, 5, 5, 'And who while available fire doctor.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 2, 1, 1, 'Floor citizen tend across late billion turn white.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 1, 4, 3, 'Under character determine already professor letter.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 2, 3, 1, 'Become animal against fire.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 5, 3, 1, 'Article floor game.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 3, 5, 4, 'Four western concern concern.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 1, 2, 3, 'Life by Mr success.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 2, 4, 5, 'Answer situation writer.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 3, 2, 3, 'Within by plan center state outside food source.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 4, 4, 2, 'Challenge successful interesting.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 3, 3, 3, 'Weight detail health.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 4, 1, 2, 'Forward card civil same man growth include.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 1, 4, 2, 'Center standard continue at movie step beautiful.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 5, 5, 1, 'Boy improve agreement too clearly.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 5, 3, 3, 'Soon treatment plan key soon.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 3, 5, 5, 'Effect study TV little each eight know no.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 1, 4, 4, 'Difficult account staff change beautiful.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 1, 1, 4, 'Police financial trade scientist her.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 3, 1, 4, 'Approach TV room take.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 5, 4, 2, 'Office call front affect.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 2, 4, 4, 'Into law store any onto prove.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 5, 2, 1, 'Film along bag book.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 3, 1, 5, 'Evening improve official sing whom ask learn.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 3, 3, 3, 'South third candidate official.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 3, 1, 1, 'Least wait mean position.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 3, 3, 1, 'Tend police oil would build yet represent far.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 5, 2, 3, 'Kitchen call threat.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 1, 1, 4, 'Food couple away wrong add hospital company.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 2, 4, 3, 'Home decide remember with continue pressure.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 4, 1, 3, 'Traditional political commercial project method any miss.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 4, 5, 3, 'Represent bill lose never.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 5, 1, 4, 'Final heavy computer audience picture institution.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 4, 1, 1, 'What fast often down fund whole.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 3, 5, 4, 'Bill city wind marriage trade community beautiful.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 3, 2, 2, 'Perhaps likely air pretty four event partner.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 3, 2, 4, 'More ready science ever ask view.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 3, 1, 1, 'Just store skill energy them each service.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 5, 4, 1, 'Want reflect above chair theory guy development career.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 1, 4, 2, 'Single few above itself wall from person.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 2, 3, 2, 'Street cup husband loss information.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 5, 3, 4, 'Agreement anyone economic force because against everybody paper.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 2, 5, 4, 'Military save officer leave.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 5, 1, 5, 'Cause friend late down hear.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 3, 3, 4, 'Parent oil hand machine become.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 3, 4, 1, 'Ball camera nation worry source.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 3, 1, 2, 'Such war land capital outside time.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 4, 2, 2, 'Mrs expect painting inside write but apply.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 4, 3, 2, 'Must recognize bed behind yeah.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 1, 5, 3, 'Mission fly water both final strategy.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 1, 1, 5, 'Month himself serve hold fact.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 2, 3, 2, 'Similar hope ball line bill very.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 4, 3, 1, 'Congress attention defense year until.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 5, 1, 3, 'Realize I oil plant mean table.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 5, 1, 3, 'Everyone green treat knowledge.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 4, 3, 5, 'Authority number cause environment.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 5, 2, 1, 'Religious spend campaign new.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 4, 2, 1, 'Commercial speech attorney director this.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 1, 2, 2, 'Understand citizen agency city.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 3, 5, 5, 'Newspaper approach final approach property.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 4, 4, 4, 'Cup whole idea billion food toward truth.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 3, 1, 1, 'Skin quickly whose fly specific.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 1, 2, 2, 'Kid throughout across soldier easy.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 3, 2, 5, 'Feeling your century teacher mission national finish.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 4, 1, 3, 'Seek national gas part continue put last.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 5, 2, 4, 'Rather responsibility piece.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 3, 4, 5, 'Share director page box decision blue.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 3, 2, 4, 'Address course per board.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 4, 3, 5, 'Probably see officer happy respond.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 3, 3, 2, 'Go shake camera show.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 2, 4, 5, 'Them service why four of.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 2, 3, 5, 'Country travel true require human dog.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 3, 4, 2, 'Fast its prevent election.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 5, 2, 1, 'Or away explain since hot.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 5, 4, 4, 'Recent I nice standard health black affect.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 4, 5, 1, 'Attorney movie guess foreign evidence during short.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 5, 3, 5, 'Try black main town whatever.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 3, 2, 1, 'Radio wife performance political audience next.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 2, 5, 5, 'Boy whose must just range consumer sign.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 3, 3, 5, 'East clearly sing strategy three.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 1, 5, 4, 'Democrat nothing themselves this team administration.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 2, 5, 1, 'Really lay note art record.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 4, 5, 1, 'Around hope somebody deal something piece.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 4, 3, 4, 'Open law cell baby positive.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 4, 3, 4, 'They issue think century.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 4, 4, 2, 'Meet star bag student natural son security.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 5, 5, 3, 'Day bank none let.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 1, 4, 5, 'Painting democratic report sell course.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 1, 1, 5, 'Body Democrat wife manage medical thank social.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 3, 4, 1, 'Physical arm gun decision bill president memory.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 2, 1, 3, 'Face go land military political life.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 2, 4, 5, 'Big treat student enough suddenly family.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 2, 2, 2, 'Would in really traditional war.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 5, 5, 3, 'Trade morning miss yes listen no.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 3, 2, 4, 'Even miss loss save.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 3, 2, 1, 'Blue speak candidate staff cost realize.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 2, 4, 4, 'Police eat weight someone.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 1, 2, 5, 'Activity minute discuss.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 2, 3, 1, 'Yet style listen executive black.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 5, 5, 4, 'Economy catch safe around level season health born.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 2, 5, 2, 'Door beat control.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 2, 1, 1, 'Style word half deal she reflect.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 1, 3, 4, 'Task feeling box under.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 5, 3, 5, 'Financial wind everything page able.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 1, 1, 3, 'Hold hit indeed whom truth later.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 4, 4, 1, 'Yes nice major sense.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 1, 4, 5, 'Explain between particular often campaign.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 5, 4, 1, 'After tax discover shake.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 5, 2, 1, 'Local we like stage garden eat.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 1, 1, 5, 'Here enter rule together.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 4, 5, 2, 'Low kid than candidate sometimes anything light.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 2, 3, 5, 'Nearly treat nice population.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 3, 4, 3, 'Above relate natural will source two significant.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 4, 2, 2, 'Bill base region provide daughter I pattern.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 4, 2, 2, 'Somebody attack impact.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 4, 1, 5, 'Over though remain then show many.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 5, 5, 3, 'Fact financial science around situation identify.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 3, 4, 1, 'Head nothing watch difference week.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 2, 3, 3, 'Opportunity early both also finish smile.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 2, 3, 1, 'Child leave face keep ready police kind.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 1, 2, 2, 'Body finally wear money fear value short.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 1, 2, 4, 'Positive out including fine join argue.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 2, 5, 4, 'Education reflect nor.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 2, 3, 1, 'Similar from quality whom require she simple.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 3, 4, 4, 'Purpose understand blue point hit.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 2, 4, 1, 'Else side sound pattern.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 2, 3, 2, 'Pay home read state remember.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 3, 5, 5, 'High kitchen voice play former study remain.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 1, 3, 4, 'Change street yet wear true cost.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 3, 4, 3, 'This happy nice animal onto culture.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 5, 5, 2, 'Story power character.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 2, 1, 1, 'Language bag with suggest camera company.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 3, 4, 3, 'Program party build stock.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 3, 3, 5, 'Give loss artist sport.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 1, 2, 5, 'But white pick scene.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 4, 3, 2, 'System worker evening especially left allow.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 5, 2, 3, 'Executive painting music price blue person week including.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 4, 1, 4, 'Role task there guy actually see success.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 4, 2, 3, 'Serve smile from.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 4, 3, 4, 'Enjoy difference behind employee fast.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 1, 5, 4, 'Site know professor significant economy.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 4, 4, 4, 'Father away mention argue it although beyond.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 5, 2, 2, 'Always arm without magazine.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 1, 4, 1, 'Sound mind out party hot son room similar.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 4, 1, 2, 'Want support represent Democrat population might study most.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 3, 5, 5, 'Maybe his edge.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 5, 3, 4, 'By his any head should health once.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 3, 5, 2, 'Section talk run wrong work.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 3, 4, 2, 'Go sing kind key its these card.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 5, 2, 4, 'Growth candidate able apply local picture him system.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 4, 5, 2, 'Ever worry west expect physical to my official.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 2, 2, 3, 'Worry else education fall.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 3, 4, 4, 'Bad court plant kitchen operation matter usually.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 5, 4, 1, 'Federal Mr them theory.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 4, 5, 1, 'Left central though speak.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 4, 3, 3, 'Person executive beyond wear level his per.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 1, 5, 1, 'Coach design style story heavy trip.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 5, 2, 3, 'Day dark listen power.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 5, 4, 4, 'Then grow government whole fall.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 1, 4, 1, 'Reason example along improve husband easy you.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 4, 1, 1, 'Though form language.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 1, 1, 3, 'Third offer their bill again.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 1, 4, 1, 'Before time book debate sister eat.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 1, 4, 2, 'Newspaper black affect ten new.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 2, 2, 3, 'Ready carry seek small listen success.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 4, 2, 1, 'Point charge boy the material nor threat.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 2, 3, 3, 'View during somebody parent color administration behind leg.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 3, 4, 2, 'His town set suggest quickly last lose.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 4, 3, 2, 'Go to article second.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 5, 2, 3, 'Security style these teach.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 3, 3, 2, 'Table man offer information personal.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 4, 5, 4, 'Fish police necessary within perhaps process writer star.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 1, 1, 3, 'Past teach this similar show education.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 5, 4, 1, 'School at head approach green hear.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 4, 5, 2, 'Ok heart ability couple dinner include.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 1, 2, 2, 'Discuss attention so decision one themselves both.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 5, 2, 2, 'Physical pick deal hard PM.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 5, 5, 4, 'Ball food light understand begin have figure.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 1, 4, 5, 'Human wind high inside recent.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 5, 3, 2, 'Similar week black write against as.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 1, 3, 5, 'Later send interview hit.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 3, 1, 1, 'Beautiful pick support charge let meeting future.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 1, 5, 2, 'Four respond receive media.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 2, 3, 3, 'Few method find race southern sing why get.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 3, 2, 5, 'Peace inside tax also guess six trade.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 3, 4, 1, 'Each live whom.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 4, 4, 4, 'Despite generation player man image least might.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 5, 3, 5, 'City machine company coach eat about beautiful.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 3, 5, 2, 'Structure enjoy up care item movie.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 1, 3, 3, 'Lead view toward history.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 5, 4, 3, 'Study individual we outside also.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 3, 4, 2, 'You evidence reach concern relationship.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 2, 3, 4, 'Water yourself direction future effort.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 3, 4, 1, 'Buy perhaps heavy Mrs peace.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 2, 5, 3, 'Power travel lead three.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 4, 4, 3, 'Away east daughter line home total.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 5, 3, 5, 'Carry side city leave such task source.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 4, 3, 1, 'Lot well entire maintain.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 4, 5, 3, 'Speak do sure country but politics.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 3, 1, 1, 'Nice article how current expert item.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 5, 3, 1, 'Available development maybe off somebody.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 3, 3, 2, 'Necessary marriage during where stuff change.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 2, 1, 1, 'Too training energy religious through body simple.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 3, 4, 1, 'Since natural food with director green.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 3, 4, 3, 'Small action future yard current become.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 4, 1, 2, 'Professor scientist friend before season able quickly.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 1, 3, 2, 'Still offer feeling she.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 2, 2, 5, 'Eat bag source.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 4, 5, 1, 'Recently house may be.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 1, 4, 2, 'Generation plant class themselves table.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 3, 1, 5, 'Sure pull short.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 3, 4, 4, 'Party pass town national chance act war.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 5, 2, 4, 'Water water music.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 3, 1, 3, 'Writer market many thousand even ready.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 2, 5, 3, 'Program future available they culture field.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 5, 3, 3, 'Traditional month anything move we.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 5, 5, 1, 'Sea note last article mind few enter.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 1, 4, 3, 'Food everything chair lead charge.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 1, 5, 3, 'Get that add.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 4, 2, 5, 'Very turn area chair.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 3, 3, 4, 'Method pattern them occur top past.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 1, 3, 5, 'Pick leader third officer change ball note.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 5, 3, 1, 'Interesting something including.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 1, 1, 4, 'Really maintain plan four blue.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 3, 4, 4, 'Wide civil rule wonder finish particularly.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 4, 1, 2, 'Very hear administration six receive only.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 1, 4, 3, 'Fear result discover size morning education president.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 2, 5, 4, 'Policy list throw main despite enough candidate.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 5, 3, 1, 'Series admit page source new.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 5, 2, 5, 'Prevent into quickly subject customer camera store agency.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 5, 3, 3, 'Development put road new design late.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 4, 3, 2, 'Special white history.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 5, 3, 5, 'Television second network have about as.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 1, 4, 4, 'Avoid may house big field theory turn.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 2, 5, 2, 'Say cell money.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 5, 4, 1, 'Box hair spend sort.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 1, 2, 4, 'Foot little career style international fish cold.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 2, 5, 3, 'Here quickly learn spend.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 1, 1, 2, 'Realize Republican order serve.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 1, 2, 2, 'Various page maintain only mind responsibility rest.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 1, 1, 3, 'Both suggest this half.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 3, 2, 5, 'Total force American card music relate kitchen.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 1, 5, 3, 'Course never measure enjoy physical over.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 4, 1, 3, 'Boy daughter fire behind.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 4, 5, 4, 'Well book theory really system maintain.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 3, 1, 5, 'Can carry herself traditional avoid.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 2, 4, 2, 'Similar fund amount around single plan.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 5, 2, 4, 'One start series area company.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 4, 3, 5, 'These some paper water fish mission edge.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 1, 2, 2, 'Small produce list various.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 1, 3, 4, 'Record Mrs top development.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 2, 5, 4, 'Ago work upon yeah we.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 1, 4, 1, 'Worry I hour will be nice.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 3, 2, 2, 'Professional war rise yet court husband one.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 1, 4, 2, 'Movement describe if stuff American guess important book.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 5, 1, 2, 'Government rich what authority life benefit by difference.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 4, 5, 3, 'Expert wait history cover.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 1, 1, 1, 'Bad focus people stock American former ok nice.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 3, 1, 5, 'Memory minute after everyone police.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 4, 5, 4, 'Boy mind allow deal try and.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 2, 5, 1, 'Any catch care term quite month.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 2, 1, 1, 'Several almost five most sport.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 1, 4, 4, 'Whether toward magazine service join firm experience.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 2, 1, 1, 'Suffer thank line walk effect common.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 5, 1, 4, 'Claim nor too tax reach after nor establish.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 4, 5, 4, 'Key discuss prepare Republican particular per.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 4, 5, 4, 'Wear national score until.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 1, 2, 5, 'Piece draw science really.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 2, 4, 4, 'Accept decide his remain.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 2, 5, 3, 'Hand reason management response continue.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 1, 4, 1, 'Respond machine poor whose have south international.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 4, 1, 4, 'Study data clear read.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 4, 5, 3, 'Stage its husband everyone.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 5, 3, 3, 'Easy Congress dinner dinner set nice.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 3, 5, 4, 'Computer yard five performance.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 3, 1, 4, 'Impact everyone single.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 1, 1, 4, 'Main same community myself ball interesting development.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 5, 3, 5, 'Maintain city area baby stand interesting thought.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 2, 2, 2, 'Opportunity guess shoulder expect.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 1, 2, 1, 'Live media still.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 3, 5, 4, 'Water behind realize turn attorney.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 5, 1, 4, 'Republican everybody thing.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 5, 3, 1, 'Food military identify and.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 4, 3, 4, 'Lot activity produce visit.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 3, 5, 2, 'Degree return board.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 1, 5, 2, 'Put ask specific plan.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 4, 1, 1, 'North commercial music billion figure but executive.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 4, 1, 2, 'Office treat science.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 4, 1, 1, 'Official team policy response event investment sign.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 4, 1, 5, 'Front local tax play draw federal must.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 2, 3, 5, 'Most item mission issue.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 1, 2, 1, 'Everyone accept from what.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 1, 2, 4, 'Wind safe ok pretty third.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 5, 1, 4, 'Box will significant information suffer card carry structure.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 3, 5, 5, 'Door cut employee law example seat his both.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 5, 4, 3, 'Sport child drop.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 3, 5, 3, 'Provide eye far trouble store certainly.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 1, 3, 1, 'Job food movement hold couple mention herself value.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 3, 5, 4, 'Tv floor science capital.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 4, 4, 5, 'Power almost mind.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 1, 2, 1, 'Table recent market make whom evidence.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 5, 4, 5, 'Yeah position century rule result people relate.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 5, 2, 5, 'Official poor cost song.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 2, 4, 1, 'Mention until country rather put why.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 4, 4, 4, 'Mother interview identify pull wall matter.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 1, 3, 2, 'Cause eye which sometimes explain.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 2, 5, 3, 'Fear what general prevent you her will.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 4, 1, 5, 'Wish product make role play.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 2, 2, 3, 'Fire officer sort thank attention question.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 2, 2, 2, 'Need drop important kind.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 2, 2, 4, 'Reveal individual note small.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 4, 2, 4, 'Amount keep represent generation professor quickly produce trade.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 5, 3, 5, 'Education standard little beyond garden investment evidence.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 4, 5, 3, 'Traditional cultural behind area without religious environmental.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 1, 1, 5, 'Form which especially full according three.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 3, 3, 1, 'Trip act four nor easy.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 2, 3, 5, 'Seat citizen just the.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 1, 3, 5, 'Nature sense who rock century offer culture describe.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 4, 2, 4, 'Area put executive national economy.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 4, 5, 4, 'West stay pattern several chance serious technology.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 4, 4, 1, 'Which education nation bar.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 4, 3, 3, 'Public really kitchen cost.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 5, 5, 4, 'Successful need measure include sport party.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 2, 3, 2, 'Office himself politics debate road radio high first.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 1, 4, 1, 'Own production find box.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 3, 3, 2, 'Option decide threat something pattern recent.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 2, 3, 5, 'Entire large fear seem paper want.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 4, 5, 1, 'Garden keep perform house method budget coach.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 5, 4, 2, 'Policy keep magazine team week resource job.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 1, 4, 5, 'On generation agree concern.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 2, 2, 3, 'Break also race cost third model.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 4, 4, 5, 'Describe summer responsibility.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 3, 3, 3, 'Usually reason decade necessary movement citizen.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 2, 1, 5, 'Speak administration third only simple analysis baby.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 3, 3, 1, 'Walk exactly school.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 5, 1, 3, 'Of energy away others possible describe morning.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 3, 4, 1, 'Reason cell special big court region.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 1, 3, 4, 'Summer sing image song.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 1, 1, 5, 'Style service house often article property character.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 3, 3, 1, 'Beautiful believe show picture share nature vote.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 3, 2, 2, 'Let travel feel central similar.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 1, 2, 2, 'My newspaper pick major administration alone skill.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 4, 3, 2, 'Apply compare without unit involve consider either.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 5, 2, 1, 'Theory goal democratic seek.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 4, 4, 3, 'Create their same teach paper.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 2, 3, 4, 'Hear necessary early easy physical.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 3, 5, 2, 'Choice force floor practice wife across.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 2, 2, 4, 'Owner call wonder form.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 4, 2, 2, 'Receive reveal cut condition just traditional.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 1, 5, 5, 'Government out light.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 4, 5, 5, 'Question ten system relate institution.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 4, 3, 2, 'For while one position.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 5, 3, 5, 'Likely over become.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 2, 3, 5, 'Girl wall sit next.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 1, 4, 4, 'Raise agree court situation everybody like majority.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 4, 3, 3, 'Wonder lead chance individual understand citizen save.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 5, 4, 4, 'Figure few understand particularly matter.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 1, 2, 2, 'Away of already camera together Republican student.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 3, 2, 5, 'Clearly security world compare share hope.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 2, 1, 3, 'Become health discuss operation.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 3, 4, 5, 'Young through that consumer my.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 5, 3, 4, 'Compare attention coach very piece really.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 5, 5, 4, 'Themselves themselves issue have.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 3, 3, 3, 'Improve young short answer drug.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 4, 5, 5, 'World best identify in list.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 5, 5, 2, 'Open turn financial job reflect.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 2, 3, 2, 'Half article just particularly brother.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 4, 4, 4, 'Wall society court.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 3, 4, 4, 'Change may prevent rest.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 1, 4, 2, 'Low where fall effect world.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 5, 3, 2, 'Central yeah experience go parent most according.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 3, 2, 1, 'Situation action lose fly lay family hard.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 3, 5, 3, 'Pick face first series toward hour one.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 2, 2, 1, 'Analysis enjoy sure change human also realize.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 2, 3, 4, 'Idea why choice director great.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 4, 3, 3, 'School worry run try poor.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 2, 2, 2, 'Learn bad goal hand.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 4, 5, 3, 'Personal behavior can return common.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 2, 1, 1, 'Personal amount year great change different seem.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 4, 1, 1, 'Born person option family do side.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 3, 2, 3, 'Positive serious another yes.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 5, 2, 5, 'Threat director reach name camera one PM trouble.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 5, 2, 2, 'Media development cell free doctor apply parent often.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 5, 5, 2, 'Camera goal brother.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 4, 2, 3, 'Even night much wear.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 4, 2, 3, 'Point couple miss blue involve eat play.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 2, 1, 4, 'Production main him so for too.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 4, 3, 3, 'Around good lawyer red.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 5, 2, 4, 'Thing occur walk.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 3, 3, 1, 'Year way class although city.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 1, 4, 3, 'Compare ground sure product.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 2, 2, 5, 'Information poor third speech admit human.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 3, 3, 4, 'Accept that race imagine foreign.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 5, 3, 1, 'Real before cover how.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 1, 2, 4, 'Reality four catch.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 3, 1, 1, 'Important to role nor away.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 1, 2, 3, 'None stay report exactly from ok present.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 1, 4, 1, 'Heavy today concern read.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 5, 5, 3, 'Read deal discover purpose read one recent.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 3, 2, 3, 'Value majority join.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 5, 5, 2, 'With garden others court mother team garden.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 5, 2, 2, 'Without heart rest building per property guy party.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 4, 2, 1, 'Admit individual so laugh community.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 2, 2, 3, 'Still situation hear bad necessary effect.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 1, 5, 2, 'Spring rather everything eight cover agree design live.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 3, 5, 4, 'Treat not light beyond language capital fine.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 5, 1, 5, 'Ability check purpose.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 2, 3, 4, 'Never professional him of identify pick.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 5, 4, 2, 'Lead nearly among audience agreement chair.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 3, 4, 5, 'Medical room attack woman now step.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 1, 5, 4, 'Huge series six court either now.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 1, 5, 3, 'Week issue mention eight event important know rest.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 4, 3, 3, 'Difference ask computer however stop mean continue.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 4, 1, 1, 'Finally detail both director four.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 3, 3, 1, 'Vote kind the card area.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 2, 4, 2, 'Term benefit feeling discuss.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 2, 1, 3, 'Enjoy day somebody none PM throughout floor people.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 4, 3, 4, 'Throw tough why road evening question.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 3, 4, 2, 'Lose support myself none watch save.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 2, 3, 5, 'City enter upon which million thing not.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 5, 5, 3, 'Red meet management book police she nation.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 4, 1, 3, 'Ever television put address order age.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 2, 2, 4, 'Type entire practice discover wife.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 4, 2, 5, 'Station light five might agency quality effort institution.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 2, 3, 5, 'Accept crime step community ability economic.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 2, 4, 5, 'Discover seat group too in phone.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 4, 2, 4, 'Space institution it stage find action.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 1, 5, 2, 'Thousand bad suffer.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 4, 4, 4, 'Full beyond those leave share direction.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 4, 4, 2, 'Dog half both the stay college.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 2, 4, 2, 'Near hold money people scientist page anything.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 1, 5, 4, 'After teach girl small.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 1, 3, 2, 'Fly laugh lead here.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 5, 3, 5, 'Put star moment spring manage here list treatment.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 4, 4, 4, 'Political only that here maintain.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 2, 1, 4, 'Her gun military yard blue someone woman.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 1, 3, 1, 'Commercial create trouble figure make up safe.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 3, 2, 3, 'Name month market draw dream leg.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 1, 4, 4, 'Deal information whose clear how end.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 5, 5, 4, 'Many from camera east institution drive.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 1, 5, 2, 'Character college meeting something beat.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 4, 3, 3, 'Mouth summer get effect region structure.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 2, 3, 3, 'A manager certain whole.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 2, 4, 3, 'Sign determine call leg feel.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 3, 5, 3, 'Final itself seat lawyer receive cover.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 2, 1, 5, 'Create as level ever.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 4, 3, 2, 'Hope employee who sing down.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 4, 3, 4, 'Mouth treat he religious cost task center.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 5, 1, 2, 'Expert statement according organization.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 2, 4, 2, 'Also same red bring.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 3, 2, 5, 'Why light ready pull.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 5, 4, 4, 'Activity but tend dog major.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 4, 5, 1, 'Stand building pick factor particularly study.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 5, 5, 5, 'Style agreement movement new event back catch.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 5, 1, 4, 'Unit price beautiful rich share.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 2, 3, 1, 'Stop investment as bit along push.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 1, 4, 5, 'Down get Mrs here.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 5, 4, 1, 'Along write back around real authority strong.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 3, 3, 1, 'Modern first customer western exist style card.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 5, 2, 5, 'North while against trip without.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 4, 1, 1, 'Company we good approach call finally.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 3, 3, 4, 'Half make gun treat.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 4, 4, 1, 'Artist case relate method many.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 3, 1, 5, 'Human try particularly ability book drive.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 1, 2, 3, 'Behavior protect instead draw.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 1, 1, 2, 'Movement fill also head subject organization.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 4, 5, 2, 'Business white soldier question.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 1, 3, 2, 'Fly level new morning car.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 1, 1, 4, 'Environment PM use.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 4, 3, 3, 'Laugh present rich name thing.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 2, 5, 2, 'Edge week visit treatment.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 4, 5, 1, 'Better east building song military.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 5, 2, 4, 'Appear much better chair.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 3, 3, 3, 'Style red food choose west data however our.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 5, 2, 1, 'Science woman without start.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 3, 1, 4, 'Consider once walk discussion be age.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 2, 2, 5, 'Share military left spend consumer.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 4, 3, 5, 'Or dog upon.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 3, 2, 4, 'Maybe industry sell budget entire.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 4, 4, 4, 'Series very role.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 3, 5, 4, 'Upon bad house pretty something former.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 3, 4, 3, 'Foreign him or feel traditional already drive.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 3, 3, 5, 'Off citizen beat present management final.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 3, 3, 2, 'Reality report choice hear research see method.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 2, 4, 3, 'Before eat above.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 4, 1, 1, 'Meeting shoulder cause hair itself give control.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 3, 3, 5, 'Score detail sister.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 1, 3, 3, 'But treat lead ball.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 5, 5, 1, 'Early attack put.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 2, 2, 4, 'North agency by bill character.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 5, 2, 3, 'Republican play relationship threat.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 2, 3, 4, 'Method particular hard much although suffer vote.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 1, 5, 3, 'Rather area total high minute question bring.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 4, 4, 4, 'Food drive other talk.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 5, 3, 1, 'Serious plan statement outside look side.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 4, 1, 3, 'Together risk hotel.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 3, 3, 3, 'Ever ready opportunity hair like.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 3, 3, 1, 'Politics see interesting guy Democrat war.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 4, 1, 5, 'Order win by.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 4, 1, 4, 'Loss relate stand represent finish memory.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 3, 5, 1, 'Involve ground head white easy nature tree.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 3, 4, 1, 'Staff number cost television his challenge six.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 5, 3, 5, 'Stay rest western lay sure.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 4, 4, 2, 'Rock property tree Democrat various.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 5, 3, 4, 'Buy month Mr build serious pull test.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 5, 5, 3, 'Present will music plan deal.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 4, 4, 4, 'View save son record quality phone model start.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 4, 2, 3, 'In instead program have production.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 2, 4, 4, 'Season feeling language social college policy me paper.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 1, 2, 4, 'Close point style admit resource three firm.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 3, 3, 3, 'Current huge fight.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 3, 1, 2, 'We develop join support not and.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 2, 4, 4, 'We key read friend save scientist glass.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 3, 4, 4, 'Film kind bed market maybe end account leave.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 3, 5, 5, 'Good American however.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 2, 5, 5, 'Under position debate short land.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 3, 1, 2, 'Oil middle speech field management never or.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 4, 4, 5, 'Fire game mention choice.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 3, 4, 3, 'Modern her admit happen.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 4, 3, 1, 'When plan while raise likely.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 3, 1, 4, 'Fight seat attack.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 3, 1, 1, 'These through push contain.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 3, 2, 1, 'Site boy occur tonight today involve him.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 5, 5, 2, 'Story support why no company east live.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 3, 3, 4, 'Do lot white.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 2, 5, 3, 'Above sell resource prevent.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 4, 2, 4, 'But arrive school more group whether.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 3, 4, 5, 'Resource cultural thank medical task voice.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 2, 3, 1, 'Analysis month every be red accept yourself.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 1, 3, 4, 'Until life allow miss finally social part.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 1, 5, 3, 'Message exactly whose what bit sea.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 5, 3, 3, 'Statement base fall investment issue very happy safe.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 1, 2, 2, 'Who husband list.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 5, 5, 2, 'South eight member happen everyone.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 5, 3, 2, 'Candidate once eat report.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 3, 3, 5, 'Hair leg catch expect explain.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 1, 3, 4, 'Note degree section finally own especially.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 2, 2, 4, 'Structure similar attention never any.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 2, 2, 1, 'Civil exist body care high memory western.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 4, 5, 3, 'Part who more.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 5, 2, 1, 'Quickly card former real beyond.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 4, 3, 4, 'Expect response world million.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 4, 2, 4, 'Member everything century local.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 1, 3, 5, 'Would chance administration once on guess do.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 3, 4, 3, 'Put if here respond voice enough daughter.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 5, 4, 3, 'Rise land should.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 5, 1, 2, 'Pretty tough mission.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 2, 2, 5, 'Office far easy any ability long business.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 5, 5, 5, 'Operation impact road.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 3, 5, 5, 'Growth early company response character someone.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 4, 4, 2, 'Anyone material next may season meet give.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 1, 3, 3, 'Scene check return physical what.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 3, 4, 2, 'Heart hundred role grow threat safe.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 2, 1, 5, 'Take stay team animal skin measure.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 1, 1, 1, 'Since carry low be.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 1, 5, 4, 'Kid prepare reflect always south manager.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 5, 2, 3, 'Old baby blood past mother.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 3, 3, 2, 'Least carry like heavy newspaper cut wait during.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 4, 5, 3, 'Front letter network light.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 2, 2, 2, 'Hit age often decision miss edge.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 2, 2, 3, 'Billion no charge television.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 5, 4, 3, 'Phone number see stage front.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 3, 5, 2, 'Reality such total make suggest include support work.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 1, 2, 5, 'With account process little couple only.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 5, 5, 3, 'Public similar study.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 1, 2, 4, 'Bill high newspaper fill.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 3, 3, 2, 'Activity field important begin serious.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 5, 2, 2, 'Appear begin of discover.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 2, 3, 2, 'Must weight ahead mean when.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 5, 2, 5, 'Page also should along.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 5, 5, 5, 'Wind agency yard prove morning couple seven.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 2, 3, 1, 'Manager into concern agency.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 2, 4, 1, 'Behind second late fear country set choice.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 1, 4, 2, 'See fire meet garden them crime adult.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 3, 1, 2, 'Young major modern choose future tough.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 4, 5, 2, 'Base occur into support growth easy.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 2, 3, 3, 'Teacher sometimes decision growth.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 4, 3, 5, 'Bag above power purpose.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 2, 2, 5, 'Respond finish stop sometimes.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 5, 5, 5, 'Might believe act serve quickly.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 2, 4, 1, 'Live may institution risk.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 5, 3, 3, 'Mention anything sport easy eye eye.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 4, 5, 3, 'Apply notice process close lead.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 4, 3, 2, 'Back it information move week least.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 3, 2, 5, 'Must owner thus fear wide far.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 2, 5, 2, 'Memory return others long born.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 1, 5, 2, 'Like thought about buy must.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 4, 4, 2, 'Person possible product.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 4, 5, 3, 'Fill whatever they low half resource power.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 4, 1, 3, 'Total night town worker.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 1, 5, 4, 'Face here ready.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 4, 4, 3, 'Property generation member ball.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 5, 5, 3, 'Traditional no eye TV hand.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 5, 3, 4, 'Push important how.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 3, 1, 5, 'Method conference town walk plan what president visit.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 5, 3, 3, 'Next city discuss teach how back.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 3, 2, 5, 'Then bring strong will hold might.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 3, 1, 3, 'Food idea again he.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 1, 1, 3, 'We pick institution within begin.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 5, 3, 4, 'Mrs realize moment everything side.');
