INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (1, 'California Roll', 931000, 1, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (2, 'Spicy Tuna Roll', 716000, 0, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (3, 'Dragon Roll', 85000, 0, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (4, 'Rainbow Roll', 788000, 0, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (5, 'Philadelphia Roll', 370000, 0, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (6, 'Tempura Roll', 883000, 1, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (7, 'Vegetarian Roll', 996000, 0, 0, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (8, 'Salmon Sashimi', 514000, 1, 0, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (9, 'Tuna Sashimi', 741000, 1, 1, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (10, 'Yellowtail Sashimi', 738000, 0, 1, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (11, 'Octopus Sashimi', 97000, 0, 1, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (12, 'Snapper Sashimi', 529000, 1, 1, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (13, 'Mackerel Sashimi', 785000, 0, 1, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (14, 'Salmon Nigiri', 439000, 0, 0, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (15, 'Tuna Nigiri', 94000, 0, 1, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (16, 'Eel Nigiri', 602000, 0, 1, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (17, 'Shrimp Nigiri', 337000, 0, 1, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (18, 'Egg Nigiri', 597000, 0, 1, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (19, 'Crab Nigiri', 721000, 1, 1, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (20, 'Spicy Tuna Hand Roll', 839000, 1, 1, 4);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (21, 'California Hand Roll', 279000, 0, 1, 4);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (22, 'Salmon Avocado Hand Roll', 862000, 0, 1, 4);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (23, 'Vegetable Hand Roll', 557000, 0, 1, 4);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (24, 'Shrimp Tempura Hand Roll', 725000, 0, 1, 4);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (25, 'Chicken Teriyaki Bento', 710000, 1, 1, 5);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (26, 'Salmon Teriyaki Bento', 179000, 0, 0, 5);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (27, 'Beef Bulgogi Bento', 724000, 0, 0, 5);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (28, 'Vegetarian Bento', 350000, 0, 1, 5);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (29, 'Edamame', 799000, 0, 1, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (30, 'Gyoza', 426000, 0, 1, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (31, 'Seaweed Salad', 238000, 0, 1, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (32, 'Takoyaki', 975000, 0, 1, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (33, 'Agedashi Tofu', 878000, 0, 1, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (34, 'Miso Soup', 757000, 1, 1, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (35, 'Spring Rolls', 575000, 0, 1, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (36, 'Mochi Ice Cream', 404000, 0, 1, 7);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (37, 'Green Tea Cheesecake', 877000, 0, 1, 7);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (38, 'Dorayaki', 603000, 0, 1, 7);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (39, 'Matcha Panna Cotta', 554000, 0, 1, 7);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (40, 'Sesame Balls', 971000, 0, 1, 7);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (41, 'Green Tea', 586000, 0, 0, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (42, 'Sake', 260000, 0, 1, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (43, 'Plum Wine', 574000, 0, 1, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (44, 'Ramune Soda', 766000, 0, 1, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (45, 'Matcha Latte', 404000, 0, 0, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (46, 'Iced Oolong Tea', 643000, 0, 1, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (47, 'Shoyu Ramen', 624000, 0, 0, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (48, 'Miso Ramen', 115000, 1, 1, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (49, 'Tonkotsu Ramen', 700000, 0, 1, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (50, 'Spicy Chicken Ramen', 561000, 0, 0, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (51, 'Vegetable Ramen', 206000, 0, 1, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (52, 'Seafood Ramen', 329000, 0, 1, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (53, 'Gyudon (Beef Bowl)', 622000, 0, 0, 10);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (54, 'Katsudon (Pork Cutlet Bowl)', 631000, 1, 1, 10);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (55, 'Oyakodon (Chicken and Egg Bowl)', 322000, 0, 1, 10);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (56, 'Unadon (Eel Bowl)', 343000, 0, 1, 10);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (57, 'Tekka Don (Tuna Bowl)', 199000, 0, 1, 10);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (58, 'Chirashi Don (Scattered Sushi Bowl)', 597000, 0, 1, 10);
