INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (1, 'California Roll', 653000, 1, 0, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (2, 'Spicy Tuna Roll', 931000, 0, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (3, 'Dragon Roll', 862000, 0, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (4, 'Rainbow Roll', 935000, 0, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (5, 'Philadelphia Roll', 804000, 0, 0, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (6, 'Tempura Roll', 993000, 1, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (7, 'Vegetarian Roll', 800000, 0, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (8, 'Salmon Sashimi', 261000, 0, 0, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (9, 'Tuna Sashimi', 856000, 0, 1, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (10, 'Yellowtail Sashimi', 395000, 0, 1, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (11, 'Octopus Sashimi', 613000, 0, 1, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (12, 'Snapper Sashimi', 379000, 0, 1, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (13, 'Mackerel Sashimi', 251000, 0, 1, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (14, 'Salmon Nigiri', 588000, 0, 1, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (15, 'Tuna Nigiri', 264000, 0, 1, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (16, 'Eel Nigiri', 129000, 0, 1, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (17, 'Shrimp Nigiri', 169000, 0, 1, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (18, 'Egg Nigiri', 179000, 0, 1, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (19, 'Crab Nigiri', 102000, 0, 1, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (20, 'Spicy Tuna Hand Roll', 946000, 0, 1, 4);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (21, 'California Hand Roll', 381000, 0, 1, 4);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (22, 'Salmon Avocado Hand Roll', 774000, 0, 1, 4);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (23, 'Vegetable Hand Roll', 138000, 0, 1, 4);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (24, 'Shrimp Tempura Hand Roll', 753000, 1, 0, 4);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (25, 'Chicken Teriyaki Bento', 759000, 0, 1, 5);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (26, 'Salmon Teriyaki Bento', 762000, 1, 1, 5);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (27, 'Beef Bulgogi Bento', 498000, 0, 1, 5);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (28, 'Vegetarian Bento', 165000, 0, 1, 5);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (29, 'Edamame', 597000, 0, 1, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (30, 'Gyoza', 518000, 1, 1, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (31, 'Seaweed Salad', 592000, 0, 1, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (32, 'Takoyaki', 278000, 0, 0, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (33, 'Agedashi Tofu', 221000, 0, 1, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (34, 'Miso Soup', 639000, 1, 1, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (35, 'Spring Rolls', 775000, 0, 1, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (36, 'Mochi Ice Cream', 945000, 0, 0, 7);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (37, 'Green Tea Cheesecake', 251000, 0, 1, 7);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (38, 'Dorayaki', 976000, 0, 1, 7);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (39, 'Matcha Panna Cotta', 91000, 0, 1, 7);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (40, 'Sesame Balls', 338000, 0, 1, 7);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (41, 'Green Tea', 442000, 0, 1, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (42, 'Sake', 789000, 0, 1, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (43, 'Plum Wine', 532000, 0, 1, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (44, 'Ramune Soda', 842000, 0, 1, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (45, 'Matcha Latte', 104000, 0, 1, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (46, 'Iced Oolong Tea', 731000, 0, 1, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (47, 'Shoyu Ramen', 307000, 0, 1, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (48, 'Miso Ramen', 814000, 0, 0, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (49, 'Tonkotsu Ramen', 735000, 0, 1, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (50, 'Spicy Chicken Ramen', 171000, 0, 1, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (51, 'Vegetable Ramen', 280000, 0, 1, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (52, 'Seafood Ramen', 576000, 0, 1, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (53, 'Gyudon (Beef Bowl)', 662000, 1, 1, 10);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (54, 'Katsudon (Pork Cutlet Bowl)', 496000, 0, 1, 10);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (55, 'Oyakodon (Chicken and Egg Bowl)', 246000, 0, 1, 10);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (56, 'Unadon (Eel Bowl)', 173000, 0, 1, 10);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (57, 'Tekka Don (Tuna Bowl)', 176000, 0, 1, 10);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (58, 'Chirashi Don (Scattered Sushi Bowl)', 438000, 1, 0, 10);
