INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (1, 'California Roll', 681000, 1, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (2, 'Spicy Tuna Roll', 157000, 0, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (3, 'Dragon Roll', 852000, 0, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (4, 'Rainbow Roll', 863000, 0, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (5, 'Philadelphia Roll', 152000, 0, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (6, 'Tempura Roll', 569000, 0, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (7, 'Vegetarian Roll', 742000, 1, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (8, 'Salmon Sashimi', 328000, 1, 1, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (9, 'Tuna Sashimi', 797000, 0, 0, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (10, 'Yellowtail Sashimi', 649000, 0, 1, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (11, 'Octopus Sashimi', 738000, 0, 1, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (12, 'Snapper Sashimi', 197000, 0, 1, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (13, 'Mackerel Sashimi', 424000, 0, 1, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (14, 'Salmon Nigiri', 251000, 0, 1, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (15, 'Tuna Nigiri', 211000, 0, 1, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (16, 'Eel Nigiri', 117000, 0, 1, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (17, 'Shrimp Nigiri', 582000, 0, 0, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (18, 'Egg Nigiri', 471000, 0, 1, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (19, 'Crab Nigiri', 400000, 0, 1, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (20, 'Spicy Tuna Hand Roll', 813000, 0, 1, 4);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (21, 'California Hand Roll', 977000, 0, 1, 4);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (22, 'Salmon Avocado Hand Roll', 988000, 0, 1, 4);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (23, 'Vegetable Hand Roll', 589000, 0, 0, 4);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (24, 'Shrimp Tempura Hand Roll', 557000, 0, 0, 4);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (25, 'Chicken Teriyaki Bento', 448000, 1, 1, 5);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (26, 'Salmon Teriyaki Bento', 96000, 1, 1, 5);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (27, 'Beef Bulgogi Bento', 261000, 0, 0, 5);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (28, 'Vegetarian Bento', 474000, 0, 1, 5);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (29, 'Edamame', 446000, 0, 1, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (30, 'Gyoza', 672000, 0, 1, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (31, 'Seaweed Salad', 566000, 0, 1, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (32, 'Takoyaki', 374000, 1, 1, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (33, 'Agedashi Tofu', 546000, 0, 1, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (34, 'Miso Soup', 714000, 1, 0, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (35, 'Spring Rolls', 501000, 0, 1, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (36, 'Mochi Ice Cream', 502000, 1, 1, 7);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (37, 'Green Tea Cheesecake', 807000, 0, 0, 7);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (38, 'Dorayaki', 268000, 0, 1, 7);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (39, 'Matcha Panna Cotta', 481000, 0, 1, 7);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (40, 'Sesame Balls', 381000, 0, 0, 7);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (41, 'Green Tea', 906000, 0, 1, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (42, 'Sake', 809000, 0, 1, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (43, 'Plum Wine', 378000, 0, 1, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (44, 'Ramune Soda', 318000, 1, 1, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (45, 'Matcha Latte', 542000, 0, 1, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (46, 'Iced Oolong Tea', 906000, 1, 1, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (47, 'Shoyu Ramen', 484000, 0, 0, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (48, 'Miso Ramen', 474000, 0, 1, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (49, 'Tonkotsu Ramen', 611000, 0, 1, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (50, 'Spicy Chicken Ramen', 229000, 0, 1, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (51, 'Vegetable Ramen', 969000, 1, 1, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (52, 'Seafood Ramen', 790000, 0, 1, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (53, 'Gyudon (Beef Bowl)', 946000, 0, 1, 10);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (54, 'Katsudon (Pork Cutlet Bowl)', 407000, 0, 1, 10);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (55, 'Oyakodon (Chicken and Egg Bowl)', 408000, 0, 0, 10);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (56, 'Unadon (Eel Bowl)', 183000, 0, 1, 10);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (57, 'Tekka Don (Tuna Bowl)', 635000, 1, 1, 10);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (58, 'Chirashi Don (Scattered Sushi Bowl)', 398000, 0, 1, 10);
