INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (1, '(1, 'California Roll')', 145000, 1, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (2, '(2, 'Spicy Tuna Roll')', 974000, 1, 0, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (3, '(3, 'Dragon Roll')', 320000, 0, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (4, '(4, 'Rainbow Roll')', 746000, 0, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (5, '(5, 'Philadelphia Roll')', 295000, 0, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (6, '(6, 'Tempura Roll')', 455000, 0, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (7, '(7, 'Vegetarian Roll')', 773000, 0, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (8, '(1, 'Salmon Sashimi')', 484000, 0, 1, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (9, '(2, 'Tuna Sashimi')', 356000, 1, 1, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (10, '(3, 'Yellowtail Sashimi')', 165000, 0, 1, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (11, '(4, 'Octopus Sashimi')', 99000, 1, 1, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (12, '(5, 'Snapper Sashimi')', 901000, 1, 1, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (13, '(6, 'Mackerel Sashimi')', 151000, 0, 1, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (14, '(1, 'Salmon Nigiri')', 732000, 1, 1, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (15, '(2, 'Tuna Nigiri')', 179000, 0, 1, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (16, '(3, 'Eel Nigiri')', 478000, 0, 1, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (17, '(4, 'Shrimp Nigiri')', 355000, 0, 0, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (18, '(5, 'Egg Nigiri')', 349000, 0, 1, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (19, '(6, 'Crab Nigiri')', 917000, 1, 0, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (20, '(1, 'Spicy Tuna Hand Roll')', 671000, 0, 1, 4);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (21, '(2, 'California Hand Roll')', 373000, 0, 1, 4);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (22, '(3, 'Salmon Avocado Hand Roll')', 193000, 0, 1, 4);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (23, '(4, 'Vegetable Hand Roll')', 640000, 0, 1, 4);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (24, '(5, 'Shrimp Tempura Hand Roll')', 784000, 1, 1, 4);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (25, '(1, 'Chicken Teriyaki Bento')', 973000, 0, 0, 5);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (26, '(2, 'Salmon Teriyaki Bento')', 813000, 0, 1, 5);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (27, '(3, 'Beef Bulgogi Bento')', 505000, 0, 0, 5);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (28, '(4, 'Vegetarian Bento')', 593000, 1, 1, 5);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (29, '(1, 'Edamame')', 592000, 0, 0, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (30, '(2, 'Gyoza')', 427000, 0, 0, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (31, '(3, 'Seaweed Salad')', 742000, 0, 1, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (32, '(4, 'Takoyaki')', 273000, 0, 0, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (33, '(5, 'Agedashi Tofu')', 751000, 0, 1, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (34, '(6, 'Miso Soup')', 555000, 0, 0, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (35, '(7, 'Spring Rolls')', 127000, 0, 1, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (36, '(1, 'Mochi Ice Cream')', 357000, 0, 1, 7);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (37, '(2, 'Green Tea Cheesecake')', 857000, 1, 1, 7);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (38, '(3, 'Dorayaki')', 226000, 0, 1, 7);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (39, '(4, 'Matcha Panna Cotta')', 277000, 0, 1, 7);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (40, '(5, 'Sesame Balls')', 325000, 0, 0, 7);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (41, '(1, 'Green Tea')', 787000, 0, 1, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (42, '(2, 'Sake')', 654000, 0, 1, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (43, '(3, 'Plum Wine')', 698000, 0, 1, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (44, '(4, 'Ramune Soda')', 657000, 0, 0, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (45, '(5, 'Matcha Latte')', 919000, 0, 1, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (46, '(6, 'Iced Oolong Tea')', 391000, 1, 0, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (47, '(1, 'Shoyu Ramen')', 293000, 0, 1, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (48, '(2, 'Miso Ramen')', 306000, 0, 1, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (49, '(3, 'Tonkotsu Ramen')', 633000, 0, 0, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (50, '(4, 'Spicy Chicken Ramen')', 732000, 0, 1, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (51, '(5, 'Vegetable Ramen')', 834000, 0, 1, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (52, '(6, 'Seafood Ramen')', 352000, 0, 0, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (53, '(1, 'Gyudon (Beef Bowl)')', 934000, 0, 1, 10);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (54, '(2, 'Katsudon (Pork Cutlet Bowl)')', 416000, 0, 1, 10);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (55, '(3, 'Oyakodon (Chicken and Egg Bowl)')', 968000, 0, 0, 10);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (56, '(4, 'Unadon (Eel Bowl)')', 637000, 0, 1, 10);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (57, '(5, 'Tekka Don (Tuna Bowl)')', 569000, 0, 1, 10);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (58, '(6, 'Chirashi Don (Scattered Sushi Bowl)')', 585000, 0, 1, 10);
