INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (1, 'California Roll', 747000, 1, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (2, 'Spicy Tuna Roll', 289000, 0, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (3, 'Dragon Roll', 622000, 0, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (4, 'Rainbow Roll', 210000, 0, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (5, 'Philadelphia Roll', 298000, 0, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (6, 'Tempura Roll', 563000, 1, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (7, 'Vegetarian Roll', 294000, 0, 1, 1);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (8, 'Salmon Sashimi', 971000, 0, 0, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (9, 'Tuna Sashimi', 671000, 0, 1, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (10, 'Yellowtail Sashimi', 240000, 0, 1, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (11, 'Octopus Sashimi', 599000, 0, 1, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (12, 'Snapper Sashimi', 220000, 0, 1, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (13, 'Mackerel Sashimi', 274000, 0, 1, 2);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (14, 'Salmon Nigiri', 553000, 0, 1, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (15, 'Tuna Nigiri', 170000, 0, 1, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (16, 'Eel Nigiri', 129000, 0, 0, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (17, 'Shrimp Nigiri', 656000, 0, 1, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (18, 'Egg Nigiri', 94000, 0, 1, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (19, 'Crab Nigiri', 515000, 0, 1, 3);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (20, 'Spicy Tuna Hand Roll', 108000, 0, 1, 4);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (21, 'California Hand Roll', 472000, 0, 1, 4);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (22, 'Salmon Avocado Hand Roll', 420000, 0, 0, 4);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (23, 'Vegetable Hand Roll', 569000, 0, 1, 4);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (24, 'Shrimp Tempura Hand Roll', 173000, 0, 1, 4);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (25, 'Chicken Teriyaki Bento', 853000, 1, 1, 5);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (26, 'Salmon Teriyaki Bento', 828000, 0, 1, 5);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (27, 'Beef Bulgogi Bento', 716000, 1, 1, 5);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (28, 'Vegetarian Bento', 145000, 0, 1, 5);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (29, 'Edamame', 561000, 0, 1, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (30, 'Gyoza', 653000, 0, 1, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (31, 'Seaweed Salad', 287000, 0, 1, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (32, 'Takoyaki', 379000, 0, 1, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (33, 'Agedashi Tofu', 305000, 0, 1, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (34, 'Miso Soup', 963000, 0, 1, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (35, 'Spring Rolls', 272000, 1, 1, 6);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (36, 'Mochi Ice Cream', 137000, 1, 1, 7);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (37, 'Green Tea Cheesecake', 144000, 0, 1, 7);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (38, 'Dorayaki', 538000, 0, 1, 7);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (39, 'Matcha Panna Cotta', 797000, 0, 1, 7);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (40, 'Sesame Balls', 158000, 1, 1, 7);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (41, 'Green Tea', 287000, 0, 1, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (42, 'Sake', 941000, 0, 1, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (43, 'Plum Wine', 837000, 0, 1, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (44, 'Ramune Soda', 527000, 0, 1, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (45, 'Matcha Latte', 758000, 0, 1, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (46, 'Iced Oolong Tea', 532000, 1, 1, 8);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (47, 'Shoyu Ramen', 287000, 0, 0, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (48, 'Miso Ramen', 883000, 0, 1, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (49, 'Tonkotsu Ramen', 293000, 0, 1, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (50, 'Spicy Chicken Ramen', 475000, 1, 1, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (51, 'Vegetable Ramen', 795000, 0, 1, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (52, 'Seafood Ramen', 936000, 0, 1, 9);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (53, 'Gyudon (Beef Bowl)', 334000, 0, 1, 10);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (54, 'Katsudon (Pork Cutlet Bowl)', 371000, 0, 1, 10);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (55, 'Oyakodon (Chicken and Egg Bowl)', 946000, 0, 0, 10);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (56, 'Unadon (Eel Bowl)', 682000, 1, 0, 10);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (57, 'Tekka Don (Tuna Bowl)', 362000, 0, 1, 10);
INSERT INTO FOOD_ITEM (ID_Food, FoodName, Price, isAreaRestricted, DeliverySafe, ID_Type) VALUES (58, 'Chirashi Don (Scattered Sushi Bowl)', 567000, 0, 1, 10);
