INSERT INTO FOOD_TYPE (ID_Type, TypeName) VALUES (1, 'Rolls');
INSERT INTO FOOD_TYPE (ID_Type, TypeName) VALUES (2, 'Sashimi');
INSERT INTO FOOD_TYPE (ID_Type, TypeName) VALUES (3, 'Nigiri');
INSERT INTO FOOD_TYPE (ID_Type, TypeName) VALUES (4, 'Hand Rolls');
INSERT INTO FOOD_TYPE (ID_Type, TypeName) VALUES (5, 'Bento');
INSERT INTO FOOD_TYPE (ID_Type, TypeName) VALUES (6, 'Appetizers');
INSERT INTO FOOD_TYPE (ID_Type, TypeName) VALUES (7, 'Desserts');
INSERT INTO FOOD_TYPE (ID_Type, TypeName) VALUES (8, 'Beverages');
INSERT INTO FOOD_TYPE (ID_Type, TypeName) VALUES (9, 'Ramen');
INSERT INTO FOOD_TYPE (ID_Type, TypeName) VALUES (10, 'Donburi');
