INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 1, 5, 2, 'Build garden even response measure.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 3, 3, 3, 'Ever radio condition about lead maintain sound.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 5, 5, 1, 'Director down plant difference record.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 3, 4, 1, 'Reality factor PM fund majority report research just.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 5, 5, 1, 'There enough Mrs stop case school either.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 1, 3, 1, 'Threat performance she reality tax quickly half.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 3, 1, 2, 'How particularly process campaign stage both.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 2, 1, 3, 'Stand offer modern at important throughout.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 4, 5, 1, 'Which pattern risk development pull.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 5, 4, 2, 'Toward same effect road.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 2, 5, 2, 'Should type never rather candidate affect anything.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 5, 4, 2, 'Because mention spend.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 4, 2, 5, 'Space enter I prevent resource issue major.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 1, 1, 5, 'Knowledge forward outside possible back should over.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 5, 3, 2, 'Place medical rock on religious enter five.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 2, 3, 2, 'Article race hot stop occur customer drive.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 4, 2, 1, 'Alone past though morning break.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 5, 5, 3, 'Drive break write born any.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 4, 2, 4, 'Material north cultural east speech hotel manage.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 1, 2, 2, 'Prevent term west happy.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 5, 5, 2, 'Nearly since decade benefit wish past.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 3, 2, 2, 'Language purpose bring firm very store purpose.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 4, 2, 5, 'Simply sound believe wide part fact performance.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 5, 3, 3, 'Theory phone your key pressure.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 2, 2, 5, 'Air off home.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 2, 5, 3, 'Statement despite then.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 5, 5, 5, 'Child writer out movie agency.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 5, 4, 4, 'Enough choice staff possible.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 5, 3, 1, 'Day candidate attention less.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 1, 1, 4, 'Man affect cause security account ask since point.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 4, 5, 2, 'Water season different fact mouth magazine.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 5, 3, 1, 'Present amount defense local Congress hit.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 2, 5, 3, 'Sing weight dog interesting.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 1, 4, 2, 'Class official authority stay spring one professor.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 2, 2, 1, 'Serve defense degree information.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 3, 4, 1, 'Audience read many own.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 4, 4, 3, 'Student piece accept water weight white.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 4, 2, 2, 'Like under rule old situation.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 1, 3, 1, 'Around white will thank they.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 2, 4, 2, 'Who painting almost lose really beyond.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 2, 2, 4, 'People movement identify wear add beautiful.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 2, 2, 4, 'Wrong special fill.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 1, 4, 3, 'Admit field anyone sing.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 4, 2, 2, 'Difference later girl happy institution race coach.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 1, 5, 2, 'Record time health far about strategy successful.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 2, 2, 3, 'Should involve second up.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 3, 2, 4, 'Send price dog cup government party throw.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 3, 5, 4, 'Safe decide season may.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 3, 1, 5, 'Coach recognize into goal.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 5, 5, 3, 'Policy foreign through religious threat third receive.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 5, 4, 3, 'Forward heavy pattern take painting body reality.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 5, 3, 4, 'Difference determine mother ten policy place.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 4, 2, 4, 'Near to common main enough.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 4, 4, 5, 'Do quality audience support same about difficult.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 2, 1, 1, 'Professional experience become especially structure.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 1, 5, 3, 'Door minute any eat shake where identify.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 2, 3, 1, 'Start agent appear current alone any natural.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 5, 4, 5, 'Son for guy hear pick continue wait write.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 1, 4, 1, 'Attorney share hair box.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 1, 5, 1, 'Political main cause.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 4, 5, 4, 'Safe top development back act simple we.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 2, 2, 1, 'Hit thank ball use.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 3, 3, 4, 'Mind today choose within.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 3, 5, 1, 'Responsibility mention important.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 5, 4, 1, 'Far conference week maintain lay first.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 5, 3, 5, 'Get second present model.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 5, 4, 3, 'She interview pattern security interview.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 1, 5, 2, 'Write own take process until.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 2, 4, 5, 'Standard our individual international his decide person.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 2, 3, 4, 'Remain maybe nothing fight it too.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 5, 1, 1, 'Every capital good artist.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 2, 1, 5, 'Teach employee similar similar.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 2, 2, 4, 'Help artist especially avoid into baby sound.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 4, 5, 1, 'Itself nice hour court shake scene.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 4, 5, 2, 'Surface dark war finish industry.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 5, 5, 1, 'Kind will realize.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 4, 2, 5, 'Model what challenge child around up state.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 1, 1, 2, 'Product law economic book cause mention building.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 4, 4, 4, 'Born prove class wide true anything occur.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 2, 4, 3, 'Evening against develop film guy.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 4, 2, 5, 'Price with middle voice reflect.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 5, 4, 5, 'Itself site hair measure civil daughter less seek.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 5, 4, 5, 'Appear free drive.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 2, 2, 3, 'Item environment only affect why improve consider act.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 2, 4, 3, 'Myself argue director clearly fund because.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 3, 1, 2, 'Letter we check case.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 3, 4, 1, 'Wife simple back million traditional.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 3, 2, 2, 'Point outside share expert radio.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 4, 1, 4, 'Middle ask thus scene future administration pretty.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 1, 2, 2, 'Especially past great environment sea relationship.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 5, 2, 1, 'Yet industry challenge indeed write.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 1, 1, 3, 'Fact artist dinner quality.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 4, 4, 3, 'Out level at exist significant.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 2, 3, 4, 'Response here identify operation subject prove.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 2, 1, 3, 'Early themselves recognize million hold song anyone series.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 1, 3, 5, 'Wrong me practice we billion local others firm.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 5, 3, 3, 'Call TV deal daughter bring response activity statement.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 4, 2, 2, 'Probably appear another end.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 3, 5, 2, 'Meet rather week short.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 5, 1, 5, 'Goal bad moment bit many must own.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 4, 2, 1, 'Manager indeed course find I floor.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 5, 2, 2, 'Able medical entire prepare show church.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 5, 1, 4, 'Who group seek.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 5, 2, 3, 'Enter push none really stop.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 1, 4, 3, 'Table least whose performance contain role option.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 5, 2, 1, 'Age lose small tonight artist visit once.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 1, 3, 1, 'Surface door ok conference against watch attention miss.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 4, 3, 1, 'Front play hear budget.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 2, 5, 1, 'Skill practice gas any.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 2, 4, 5, 'Peace return minute avoid seven message off practice.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 1, 1, 5, 'Maybe your there paper our kitchen.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 1, 5, 2, 'Glass now traditional rich land bar Mr.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 4, 3, 3, 'Choose point we table.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 3, 5, 3, 'Safe rule well clearly.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 1, 1, 1, 'Above respond run others.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 3, 5, 1, 'Natural eight reveal nice food.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 1, 4, 3, 'Assume against method where big.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 1, 1, 1, 'Receive machine family necessary government east.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 1, 4, 4, 'Management line door who international to field.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 2, 2, 1, 'You affect thus force all.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 2, 1, 1, 'Benefit level some budget amount grow share.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 4, 4, 1, 'Great look claim these camera everyone item.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 5, 1, 3, 'Trip where along list difference.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 2, 4, 2, 'Plan receive piece partner computer decision society.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 3, 2, 5, 'Hair little recognize wind charge development former.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 3, 5, 2, 'Material article part.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 2, 5, 1, 'Exist couple station develop nothing natural.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 1, 2, 5, 'Fear loss material field practice cost.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 1, 3, 3, 'Door science past bit.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 4, 1, 4, 'Day time step environment.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 2, 4, 4, 'Those wish mother five cup.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 1, 2, 1, 'Message mention hand firm process factor husband.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 4, 4, 4, 'Source change start.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 3, 1, 3, 'Season style though next exist lead.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 5, 5, 1, 'He may tend Mrs use.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 3, 3, 4, 'Home church her spend.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 2, 2, 4, 'Amount building move impact what dinner.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 2, 4, 5, 'Road national see citizen.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 4, 4, 3, 'Guess either third.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 3, 5, 2, 'Audience treat accept wife manager ago weight six.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 2, 4, 5, 'Respond family population.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 5, 2, 2, 'Population practice artist safe there.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 5, 3, 4, 'Lay in recent market anyone between.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 3, 1, 1, 'Crime too political important.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 1, 5, 3, 'Television house hard if summer claim blood speech.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 2, 4, 1, 'Half nor affect civil director raise.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 1, 5, 4, 'Interview long ago require believe success he.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 5, 1, 4, 'Southern ago site down center concern make.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 5, 5, 3, 'Voice threat quickly memory issue create.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 4, 3, 4, 'Spring explain after argue woman suffer well.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 4, 3, 3, 'Catch least speak war present can imagine.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 4, 1, 1, 'Apply create position truth better inside rule right.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 5, 3, 4, 'Rise source water music family eight design.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 1, 1, 2, 'Law thousand score hundred everyone especially.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 5, 4, 1, 'Too mean sense tax particularly bag system face.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 1, 2, 5, 'Join story test property medical animal activity.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 5, 5, 5, 'Type notice accept to reason leader.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 1, 2, 5, 'Brother here ten guy worry whom fine describe.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 4, 5, 3, 'Leg ball three artist marriage speak here.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 5, 5, 3, 'Page similar physical common how citizen daughter.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 1, 2, 2, 'Color development edge five him feeling work always.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 2, 2, 3, 'That very together exist eye book industry.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 2, 2, 2, 'Within responsibility source red power national.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 5, 2, 2, 'Whole fly church early cold food rather.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 4, 5, 5, 'Baby own white court impact candidate seat.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 1, 4, 3, 'Now world notice relate today operation make.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 1, 1, 5, 'Something whether plant tell property against score.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 3, 1, 3, 'Focus science tree.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 2, 1, 4, 'Position occur nation seat.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 3, 4, 5, 'Provide happy develop word main there.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 2, 4, 2, 'Guess party maintain behavior tough.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 4, 1, 2, 'Analysis turn create quite.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 4, 4, 1, 'Whole it activity lose a.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 3, 4, 4, 'Away stage Congress national reduce.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 3, 1, 4, 'Half school resource recently service local already.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 3, 3, 5, 'Mouth factor time serious guess important.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 4, 1, 5, 'Record write star wrong pressure happen medical difference.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 5, 3, 2, 'Section street gun occur year television next.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 3, 1, 3, 'Set maintain take probably effort large action.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 2, 4, 4, 'Live play send commercial mission.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 3, 1, 3, 'Environmental brother similar these tell she.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 5, 1, 4, 'Heavy space inside candidate but about shoulder.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 1, 4, 4, 'Sure food she value perhaps already cell.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 1, 1, 4, 'Another side he yard adult store control structure.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 3, 4, 1, 'Conference professor skill college state.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 1, 1, 5, 'Popular vote under place.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 5, 2, 1, 'Rule side nearly close affect say.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 1, 1, 3, 'Board involve allow may.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 1, 4, 5, 'Sit nice bed step region if.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 1, 5, 1, 'Bag stuff idea.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 5, 4, 5, 'Than cell action.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 2, 2, 2, 'Behavior step animal commercial break.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 1, 2, 1, 'Over too ground husband summer natural.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 3, 2, 5, 'Candidate year real.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 4, 4, 5, 'Eight page outside need air why again.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 1, 2, 1, 'Talk affect financial on her some dream represent.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 1, 3, 5, 'Job create majority range question campaign similar.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 1, 2, 2, 'So foreign stock again dark each media.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 2, 5, 2, 'However concern black who once.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 5, 4, 2, 'Edge political truth sense staff.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 5, 5, 4, 'Necessary feeling east true speak expert.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 2, 5, 4, 'Conference have sure offer recognize cup hot.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 2, 5, 2, 'Visit act figure country analysis option.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 2, 1, 4, 'Tough wait admit unit instead.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 2, 3, 1, 'Kitchen suffer her PM opportunity natural community.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 1, 4, 3, 'Itself painting interview hit pretty matter.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 2, 1, 2, 'Visit interest thing present.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 1, 1, 5, 'Institution security yet question.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 2, 4, 1, 'Factor wonder word buy.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 1, 2, 2, 'Sister whatever white.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 4, 4, 5, 'Back watch establish night window capital simple.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 1, 1, 3, 'Sense travel people play forward professional imagine.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 5, 2, 3, 'Common agree control standard state very leg.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 2, 4, 3, 'Range anyone bed tree life yes.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 3, 1, 1, 'Voice rest again cover easy.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 1, 1, 3, 'Month bill week alone establish sing.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 5, 4, 5, 'Various lawyer hot rock just.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 4, 2, 5, 'Method stay receive hundred adult.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 1, 4, 1, 'Fall recent after road else oil.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 3, 3, 4, 'Hospital air own lawyer.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 5, 3, 3, 'East among culture less national.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 1, 4, 2, 'Buy statement finish all left wife section.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 5, 5, 4, 'Expect forward hour many time matter.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 2, 2, 5, 'At sell administration minute much choose.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 3, 1, 2, 'Cold go see sister own reflect head.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 2, 3, 4, 'Pretty instead big car rate run.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 1, 4, 2, 'Yeah star chance determine.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 5, 3, 2, 'Research list low.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 4, 3, 3, 'Six each hair likely evening.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 4, 2, 1, 'Big concern staff campaign around four head.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 4, 4, 1, 'Measure project glass statement vote.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 1, 2, 1, 'Owner door degree traditional soon.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 1, 1, 2, 'Matter right instead game factor nor happen.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 3, 3, 1, 'Heavy hand value job inside.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 2, 4, 4, 'Health Congress area international will policy region trouble.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 1, 5, 1, 'Amount cause court behavior source man agent half.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 2, 3, 4, 'Far authority check expect rather.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 2, 3, 1, 'Stuff get story market officer mother artist.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 1, 1, 5, 'Should set someone hundred ago scene blood.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 2, 1, 5, 'Door machine opportunity yet outside home major.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 5, 2, 2, 'Mention up main relationship point professor.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 5, 1, 4, 'Mrs response discussion single.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 1, 2, 5, 'Entire young certain be different change.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 5, 5, 3, 'Test moment eat myself seven sit.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 5, 2, 1, 'Ahead economy instead bank agreement.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 2, 1, 5, 'Tonight watch expect agreement agent attention.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 4, 5, 1, 'Wonder red debate require.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 4, 5, 1, 'Radio sing degree ground week night ten vote.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 2, 1, 4, 'Than relate human citizen between gun on.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 5, 5, 2, 'Western girl various tend bed.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 1, 4, 1, 'Water history customer language girl police ability.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 4, 5, 5, 'Personal business system reflect.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 2, 5, 3, 'Himself improve year.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 2, 4, 5, 'Nor prevent what baby many care despite.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 2, 1, 4, 'Everyone civil general difficult realize view.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 5, 3, 5, 'Recent lay difficult note major nature.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 1, 3, 5, 'Very over safe heavy meet land industry.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 3, 2, 4, 'Game common interest fly degree catch land fund.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 5, 5, 1, 'Toward article religious important together.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 2, 4, 5, 'Probably huge such question.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 4, 2, 4, 'Late fund left little current home.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 1, 3, 5, 'Quality international street else wind hope wonder.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 3, 1, 2, 'Station particular nor act wait move.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 5, 1, 2, 'Rate program shake cut popular.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 2, 3, 4, 'Member prevent few born get.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 2, 4, 3, 'Deal three loss lose right interest.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 4, 5, 4, 'Population west difficult manager sit sure.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 4, 4, 2, 'Ago study yeah.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 1, 3, 5, 'Manage call detail suffer method.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 4, 5, 2, 'Conference real one all offer trouble clearly.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 5, 2, 4, 'Person claim become reach day.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 5, 3, 2, 'Beyond throughout perform third themselves police federal.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 2, 3, 4, 'To information man end summer.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 3, 1, 1, 'Practice condition get seek continue provide.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 3, 4, 2, 'Box set six whose step once through produce.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 1, 3, 3, 'Soon peace begin program expert.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 3, 1, 1, 'Kid teach language current might.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 2, 4, 2, 'Win fine also any with accept reveal.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 2, 1, 1, 'Leave special sense ever best else value.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 5, 5, 3, 'Management travel guess rich reach top home road.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 2, 3, 2, 'Past blood life.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 1, 3, 2, 'Air few camera trial we.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 2, 3, 2, 'Window point respond.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 1, 4, 3, 'Wide every power news.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 5, 3, 1, 'Her exist perform animal soldier decide.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 3, 1, 1, 'Table yes adult tend popular our bad.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 1, 1, 5, 'Adult year center such.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 3, 2, 5, 'Late expert political involve democratic husband.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 4, 3, 1, 'Country identify kid production unit especially.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 2, 3, 3, 'Air sell born pull business street.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 4, 4, 4, 'Able region choice message no help.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 3, 3, 3, 'Value author home look kitchen guy foreign job.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 5, 2, 5, 'Language exist push peace.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 1, 3, 5, 'Attorney cover candidate sign share itself attorney.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 1, 5, 3, 'Will reality tough build choose great.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 4, 5, 5, 'Money box special.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 5, 3, 2, 'Rule able teach democratic whose model.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 3, 4, 5, 'Nothing moment reality third nature term.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 2, 1, 5, 'What relationship past number.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 4, 3, 4, 'Process behind discussion lot enjoy their treatment save.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 1, 3, 2, 'Art stop care go.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 2, 3, 4, 'Also skill effect education audience.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 3, 2, 5, 'Property course week various air plant general animal.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 2, 4, 1, 'Eat race like use break.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 4, 5, 1, 'Goal police film start institution form.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 1, 5, 2, 'Offer require attention dinner opportunity do.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 5, 2, 5, 'Wait account coach during base.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 5, 5, 2, 'Threat themselves necessary address purpose attorney threat.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 4, 3, 1, 'Style friend be government.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 1, 1, 2, 'Mr bag city however coach in particularly.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 2, 1, 5, 'Within north believe once ask person event.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 4, 1, 2, 'Fight crime type type also voice start realize.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 3, 5, 1, 'Which sign air TV ability.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 2, 4, 2, 'Student explain model never loss stage follow.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 5, 4, 5, 'Daughter from hundred however daughter throughout.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 5, 5, 4, 'Want my question son college seem call fill.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 1, 3, 3, 'President brother would drive pretty.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 5, 2, 4, 'Already industry office sure.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 1, 1, 5, 'Method skin break son support three.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 4, 4, 3, 'Your should goal know gun Democrat green.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 1, 3, 3, 'Reality effort same ability government.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 5, 5, 3, 'Teach statement public more near color itself.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 2, 1, 3, 'Do close least.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 5, 4, 4, 'Feeling wife case thousand president industry.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 5, 4, 4, 'Plant street crime defense happen number.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 2, 2, 1, 'Enter case choose several citizen.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 5, 5, 5, 'Agreement analysis business red firm table arm.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 2, 5, 2, 'Economy ten use where.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 1, 1, 4, 'That forget crime measure own.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 2, 1, 4, 'Up pretty career though state.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 3, 1, 4, 'Public to someone thus industry when single.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 1, 4, 4, 'Travel option voice cut which political.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 5, 1, 5, 'Standard among conference while write store.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 2, 1, 3, 'Page effort drug land bag table each.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 2, 1, 5, 'Each offer way eight minute environment.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 2, 1, 2, 'Cell deep put eight.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 3, 5, 3, 'Guess memory force defense page everyone.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 5, 3, 4, 'Operation share cup then effort.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 5, 4, 2, 'Way professor force production wonder.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 2, 4, 3, 'Guy hot site sit find thousand strategy fast.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 3, 1, 3, 'Meet hour sometimes threat ball require.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 3, 4, 4, 'Prove certain anything message.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 1, 4, 4, 'More time dream near.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 5, 1, 1, 'Under happy meet general.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 1, 3, 1, 'Close continue hour board cell.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 1, 3, 3, 'While spend travel through big live very.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 4, 5, 2, 'Happen thought best play son community able.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 1, 5, 1, 'Draw including tonight policy agent fire together.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 5, 5, 4, 'Forward partner where property about.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 3, 4, 1, 'On form senior fear right everybody race item.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 4, 1, 5, 'Almost include example.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 1, 3, 2, 'Two choice table heavy.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 1, 2, 4, 'Suggest Mrs western generation even.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 1, 4, 1, 'Prevent world east skill son.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 3, 4, 3, 'Many industry early like attorney ball right.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 3, 5, 3, 'System Republican human senior cup camera.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 5, 1, 2, 'Analysis type since you set.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 4, 5, 5, 'Save social local attention stage rich.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 1, 4, 2, 'Season create me economic as fall professor.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 2, 3, 1, 'Just meet around message defense night.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 4, 4, 1, 'Road nothing allow down.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 5, 4, 2, 'Others build need ten small else.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 5, 1, 4, 'Attack top join decade space themselves resource.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 3, 5, 1, 'Let myself true member.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 3, 2, 5, 'Around very high answer TV six strategy eat.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 2, 4, 4, 'American vote history reduce include easy.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 2, 4, 5, 'Others indeed guess friend between.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 4, 5, 3, 'Determine car phone necessary half.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 5, 5, 5, 'Age century determine operation already song.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 3, 4, 4, 'Now claim onto main.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 4, 1, 3, 'High our record decade many idea by police.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 2, 2, 5, 'Everything service effort threat by.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 1, 4, 2, 'Human maintain thank.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 4, 3, 1, 'Success despite away happen.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 1, 1, 5, 'Ball message speak form key mean court everybody.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 4, 2, 3, 'Wall risk water investment argue street free.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 4, 2, 1, 'Care stop any cover bill natural.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 4, 5, 3, 'Threat send least realize college air job.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 2, 2, 5, 'Quite list nearly.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 2, 2, 5, 'Street baby station protect.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 4, 1, 2, 'Head million pick impact beat style same.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 1, 4, 1, 'Foot wear law event green sign very.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 5, 5, 5, 'Actually base rate somebody speak.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 4, 5, 5, 'Week control power team few exactly.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 5, 4, 5, 'Significant begin major public true.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 3, 5, 4, 'Chair street full or quite car whether.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 3, 5, 3, 'Into each weight night drug.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 2, 3, 3, 'Particular range statement understand of.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 5, 2, 2, 'Want argue program leave agreement us.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 1, 3, 4, 'Only collection these to mission.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 2, 4, 3, 'Newspaper out discover become edge seem.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 5, 4, 5, 'Election matter board message individual operation.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 5, 3, 4, 'Task center choice recognize year consumer.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 1, 1, 2, 'Your later every note.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 5, 3, 3, 'Democrat east guy politics perhaps available bank page.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 2, 1, 1, 'Morning mention whether use he.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 4, 1, 4, 'Majority car tonight once paper.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 2, 2, 5, 'Authority list bank.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 5, 2, 5, 'Chair cost outside still early son.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 5, 4, 1, 'Three tend task with.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 4, 3, 4, 'High young free do expect house staff.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 5, 3, 3, 'Information food part process of its.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 2, 1, 1, 'Than candidate trial between show.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 3, 4, 5, 'Realize anyone every term think can.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 4, 5, 3, 'Especially choose bank draw former seven again.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 2, 3, 4, 'Several or him bank drive.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 1, 2, 1, 'Rich truth significant front candidate again.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 4, 4, 2, 'Hand once than business must shake sea generation.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 4, 5, 5, 'Pressure contain form.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 2, 2, 3, 'Team check water check.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 1, 4, 1, 'Respond yard stop garden recognize.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 4, 3, 5, 'Movie interview game baby sing turn environmental.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 5, 3, 2, 'Bar say born development myself recognize.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 3, 3, 3, 'Sign conference miss attorney develop.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 3, 1, 4, 'Address call dog though.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 1, 2, 1, 'Probably think present run nothing mission risk.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 5, 3, 2, 'Energy indicate particularly every represent.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 4, 4, 5, 'Civil analysis soon program contain.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 2, 1, 5, 'Involve ahead wonder sell space chance statement well.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 5, 5, 1, 'West professor play nor father just movie.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 2, 3, 3, 'Win town professional season.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 5, 3, 5, 'Song ask could important.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 4, 1, 5, 'Design indicate structure.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 3, 2, 4, 'Talk structure consider.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 2, 3, 1, 'Anything people through coach sister year.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 4, 1, 2, 'Between so skill card.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 4, 4, 3, 'Little human appear everyone oil stock reason.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 1, 4, 1, 'Free without mention.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 1, 2, 4, 'Front candidate nation fund share exactly around.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 5, 4, 1, 'Road together and home bill.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 3, 2, 2, 'Never magazine nearly allow safe.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 2, 3, 1, 'Drive laugh agree nice thank source structure.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 5, 1, 3, 'Sure opportunity group recent.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 1, 2, 5, 'Finish course five from red.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 2, 2, 1, 'Name professional off recent.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 3, 5, 2, 'Similar positive knowledge organization then bit top.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 4, 5, 3, 'Now very although top.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 3, 2, 5, 'Dream be expert wrong finally doctor.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 4, 1, 4, 'Maintain course send east participant chance.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 4, 3, 5, 'Past likely analysis list.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 5, 5, 5, 'Safe our artist responsibility.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 3, 3, 1, 'Plant theory sense response community father.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 3, 3, 3, 'Majority law bring add road raise.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 5, 5, 4, 'Million thus training American small success.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 4, 5, 3, 'Will week idea sit.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 5, 5, 1, 'Scientist much piece maybe sign throughout manage.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 3, 2, 3, 'Sense open red direction.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 2, 1, 2, 'Author clear learn fact.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 2, 4, 3, 'Send letter against about detail reason.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 3, 4, 2, 'Stuff myself stuff.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 3, 1, 3, 'Dark choose than without onto fight.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 3, 4, 1, 'Land throw such base.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 5, 2, 2, 'Between why own interest red fish decade.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 1, 4, 4, 'Defense present benefit more remember law full fire.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 3, 4, 3, 'With growth billion give.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 5, 2, 3, 'Clear others democratic worker environmental.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 3, 1, 1, 'Street all address artist they agreement guess mean.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 5, 5, 2, 'Effort they maintain middle high field painting team.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 1, 5, 2, 'Time measure author enough among deep.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 5, 3, 2, 'Remain scene your including million may.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 3, 4, 2, 'Administration own whose letter pick challenge short.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 4, 1, 1, 'Specific still scientist something concern media.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 1, 3, 1, 'Mrs per nor me.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 2, 2, 5, 'None report need dream process clear.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 1, 3, 3, 'South do white leader student never.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 2, 2, 5, 'Type measure dog Republican hair one.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 3, 1, 2, 'Down over show forward.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 5, 1, 4, 'Point beyond moment investment.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 5, 3, 5, 'Market return decide of still research station.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 4, 5, 1, 'Wonder central four subject nice protect floor.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 2, 5, 3, 'Build capital free either prepare meet.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 2, 1, 3, 'Skill everyone never trade commercial room my.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 5, 1, 4, 'Onto wear season away laugh party.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 1, 3, 5, 'Cover brother sure enjoy attorney then pull.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 3, 4, 1, 'My avoid sound personal inside than.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 1, 2, 4, 'Effect stuff mouth guess.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 4, 3, 2, 'Manager gas charge spend.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 5, 5, 1, 'Between look husband federal prepare.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 5, 3, 3, 'Child price help suffer.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 3, 1, 4, 'This tell not soon total design.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 5, 1, 5, 'Start tend put another mouth.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 1, 5, 2, 'Space across throughout.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 2, 2, 4, 'Rate piece only morning step picture film they.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 1, 3, 3, 'Edge member range environmental require operation.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 4, 3, 3, 'Court past few heart major part approach.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 3, 5, 5, 'No either garden song.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 4, 2, 2, 'Indicate enough true thousand administration visit.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 4, 2, 5, 'Rich author direction.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 2, 1, 1, 'Likely wrong blood property mean little.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 2, 3, 5, 'Better successful expect serve.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 1, 4, 3, 'Road popular everything.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 2, 4, 3, 'Personal head life community.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 2, 1, 1, 'Allow home and kid young chance.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 2, 3, 5, 'Face few quite operation someone.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 2, 5, 3, 'Customer to hot east teacher speak.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 3, 3, 4, 'Peace whether process significant.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 4, 4, 2, 'Plant method debate possible.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 2, 1, 5, 'Mouth deal talk set fear laugh teacher opportunity.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 5, 1, 3, 'Plan nice statement door.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 2, 1, 3, 'Magazine music rest room position write many room.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 2, 4, 4, 'Least tough image available field reduce.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 1, 3, 1, 'Cost whatever subject Democrat much.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 2, 5, 4, 'Special government Mrs conference lay red others try.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 2, 4, 3, 'Wait structure bad message religious.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 5, 4, 5, 'Not theory raise beautiful hundred color.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 5, 1, 1, 'Human pressure need clearly source include artist model.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 5, 4, 2, 'Wide simply discover place.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 1, 3, 3, 'Drop middle sport find.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 2, 3, 5, 'Something may serve next law anything state.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 1, 5, 5, 'Threat appear play none very position.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 4, 4, 2, 'Wonder loss street if by.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 5, 4, 1, 'Rise require word ready.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 5, 4, 3, 'Relationship into material guy language long fight.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 3, 5, 4, 'Evidence conference accept than.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 1, 1, 5, 'Effort wonder success drug role turn.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 1, 3, 5, 'Role fly yard power work.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 3, 3, 5, 'Raise theory service pick yes.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 5, 3, 4, 'By care talk range.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 3, 3, 4, 'End particularly drug serious front.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 2, 2, 3, 'Down sense factor stand practice summer.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 4, 1, 2, 'Mrs seven site full there.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 3, 3, 3, 'Interest election particularly myself finally analysis do college.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 1, 1, 2, 'House television your.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 2, 2, 1, 'Ability blue husband wall.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 2, 1, 5, 'Water meet sort hear.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 2, 5, 1, 'Add impact Republican.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 1, 1, 3, 'Eight type across middle.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 3, 5, 3, 'True past five power.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 5, 1, 3, 'Wrong apply south available.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 1, 2, 2, 'Play life and you enough.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 2, 1, 5, 'Method serve assume others.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 5, 4, 1, 'Keep another probably new ten.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 2, 1, 4, 'Officer indicate opportunity toward.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 2, 3, 5, 'Response now television particularly.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (7, 2, 4, 2, 'Executive imagine today reflect.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 3, 1, 3, 'Argue card beyond great candidate.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 4, 1, 4, 'Peace father cold cultural mention.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 3, 4, 3, 'Involve financial scene nearly serve yeah meeting.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 5, 1, 5, 'Unit away could structure full phone.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 1, 3, 1, 'North property owner his generation seek decade.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 4, 4, 3, 'Support government note exactly positive service benefit.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 4, 1, 2, 'Use step fine.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 4, 4, 4, 'Walk computer certainly remember myself.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 5, 1, 3, 'Consumer size newspaper source authority military ten their.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 3, 4, 1, 'Power majority fish staff two.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 1, 2, 2, 'Least consider measure.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 4, 3, 4, 'Far within different reflect arrive federal public.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 2, 3, 1, 'Author item election into.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 5, 2, 2, 'Poor sell arm nearly down traditional.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 3, 5, 5, 'Wrong recognize environment purpose.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 1, 2, 3, 'Manager reach debate model local each show crime.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 4, 2, 5, 'On water current actually Republican agree.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 4, 5, 4, 'Make small million down question.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 1, 1, 5, 'Similar court control head.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 5, 3, 5, 'Eat job yes rest gun how.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 1, 1, 1, 'Three attorney similar ground.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 4, 5, 1, 'Risk approach forget.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 2, 4, 4, 'Process deal order within.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 5, 4, 1, 'Include issue tend method.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 5, 5, 1, 'Instead energy speak.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (30, 2, 4, 5, 'These book least million particular.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (27, 2, 3, 4, 'Visit reflect increase issue certainly bag against.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (14, 2, 3, 2, 'Like hand reality probably local.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (11, 2, 5, 5, 'Mrs choose work within manager.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (2, 3, 2, 4, 'Process reach action however wide what quality enter.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (1, 5, 1, 3, 'Suffer cold her success role.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (37, 4, 5, 1, 'Relate yes doctor plant live box current.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (13, 5, 5, 1, 'Modern Mr class they.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (39, 3, 1, 5, 'Forward page amount walk white look.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (21, 5, 2, 5, 'Year region not hear present risk.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (28, 2, 1, 3, 'Kind free will like material campaign.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (29, 4, 2, 2, 'Least front call remain month move.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (25, 2, 1, 5, 'Beyond center wrong really reason accept.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (8, 3, 1, 5, 'Indicate tough summer address.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (22, 3, 3, 1, 'Language half how range relate professor.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (24, 4, 5, 1, 'Third challenge street prepare.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (20, 2, 4, 4, 'Happy as bag amount another bank.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (26, 3, 2, 4, 'When American water tax season star page religious.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (32, 5, 1, 3, 'Trip industry back day than attention rather.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (10, 3, 3, 3, 'Go event note begin traditional response reason energy.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (36, 1, 1, 4, 'Seven success give computer them out crime.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (19, 3, 5, 5, 'Sit past scientist heavy figure culture.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (9, 5, 2, 5, 'Base could maybe media.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (16, 4, 2, 1, 'Rest whose move week.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (4, 3, 2, 1, 'Approach agreement from college north.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (23, 5, 1, 3, 'Need conference at admit.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (3, 2, 5, 4, 'Their president industry.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (41, 5, 5, 2, 'Heavy product inside voice learn sign wide help.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (34, 3, 4, 5, 'Learn drug development water.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (12, 4, 2, 3, 'Work religious work reach wear religious sometimes.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (5, 2, 1, 2, 'Less something remember foot present edge.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (40, 3, 1, 3, 'Himself evening building kind rest challenge.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (35, 3, 2, 2, 'Have decision rest law not experience.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (15, 3, 4, 5, 'Body today wear challenge sometimes field actually.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (17, 1, 1, 1, 'Fire community red history ahead.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (38, 1, 1, 2, 'Measure adult part tough theory.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (33, 1, 3, 3, 'Me answer tend various issue leave.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (18, 3, 2, 4, 'School commercial power energy.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (31, 3, 4, 2, 'Suddenly control woman participant though media soon there.');
INSERT INTO REVIEW (ID_Review, ServiceScore, FoodScore, PriceScore, Comment) VALUES (6, 5, 2, 2, 'Tough challenge city commercial body only down.');
